### ISSUE TITLE
open file on google drive

### ISSUE THREAD

**Issue by benknaan** [jhass/nextcloud-keeweb#100]
I'm trying to config the keeweb to open a db on y gdrive.
I'm following this tutorial https://github.com/keeweb/keeweb/wiki/Dropbox-and-GDrive
But I don't know where is the config file to set Client ID  into gdriveClientId.
please advice

**Comment by jhass** [comment]
Google drive support is explicitly disabled here. Please use the hosted version at https://app.keeweb.info/ or selfhost the app according to https://github.com/keeweb/keeweb#self-hosting

**Comment by muety** [comment]
Is there a plan to support Google Drive some time in the future?

**Comment by jhass** [comment]
No.

**Comment by maurerle** [comment]
@muety Maybe if the "External storage support for Google Drive" would get fixed and updated, you could add gdrive as external storage and open keepass files with keeweb, but the project is abandoned since a few years.

**Comment by arnowelzel** [comment]
@muety The idea is to have your Keepass files stored on Nextcloud and open it from there. If you want to use Google Drive you can always go to https://app.keeweb.info/ and open your file there. Since the app only works locally in your browser this is not a security issue.
