### ISSUE TITLE
Questions and concerns about Keeweb helping my organization

### ISSUE THREAD

**Issue by keating178** [jhass/nextcloud-keeweb#104]
I have been looking into setting up Keeweb for my company to use in conjunction with nextcloud but I am running into a few concerns.
1. We have one file that 10 or so people share and it synchronizes with everyone as they use it and "cntrl+s", is this something Keeweb is able to handle?
2. Does keeweb store a local version of the keepass file in each individual user's nextcloud directory?
3. Is this meant more for everyone to use as a personal keepass, or is this something that can be shared for everyone like my helpdesk team to use everyday?

Thanks
-B

**Comment by jhass** [comment]
1. IME Keeweb handles merging databases well.
2. & 3. Shared folders are not really supported yet, see #44 Any help appreciated!

Closing this since it's just question and no open issue :)
