### ISSUE TITLE
Unable to save changes

### ISSUE THREAD

**Issue by r2p2** [jhass/nextcloud-keeweb#108]
I just installed the plugin and created a fresh kdbx file via KeePassX 2 from my Linux machine, which was synced to the Nextcloud instance.
Than I opened the file in the browser after setting up the mime type thing and tried to add some entries.

When I want to lock the file with the lock button on the bottom right, I get

> Safe Error 
> Failed to auto-save file /secure/keepass_main.kdbx on <MY URL>

At the same time, the JS console of my browser prints the following error message:

> [storage-cache] Error opening indexed db

When I click into the JS error, it says something like:

> DOMException
> "A mutation operation was attempted on a database that did not allow mutations."

What am I doing wrong?

**Comment by thrdroom** [comment]
Same here...the only two things left before the app would be working as expected: Saving changes made to the kdb-files AND saving keeweb-settings!

**Comment by lil5** [comment]
This is because your probably using FF in incognito

This is a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1562669
Which is being worked on! but is not part of this project.

**Comment by r2p2** [comment]
Seems to be true, I just checked with chromium and it works.

**Comment by r2p2** [comment]
Okay I've enabled power optimization (not sure how its actually called in the english version of Android) and I did not see any more spikes. But the "app might not work as intended". Don't know what that means.

**Comment by SimJoSt** [comment]
@r2p2 I believe the last entry was not meant for this issue, correct?

As this is not an issue of the app or Keeweb itself, this issue should be closed.
