### ISSUE TITLE
error when opening Keeweb tab

### ISSUE THREAD

**Issue by alystair** [jhass/nextcloud-keeweb#113]
```
Error loading app
Your browser doesn't support some important features we're using.

KdbxError: Error NotImplemented: AES-CBC not implemented
```

**Comment by jhass** [comment]
So what browser (and version of it) are you using?

**Comment by alystair** [comment]
Win 64 Chrome - Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by jhass** [comment]
Ah, I forgot, this is the symptom of not serving over HTTPS: https://github.com/keeweb/keeweb/issues/1100

**Comment by alystair** [comment]
ok great thanks

**Comment by Tsaukpaetra** [comment]
Would be good to detect if you're not on https and display that instead? 🤔

**Comment by maurerle** [comment]
@Tsaukpaetra its not only http vs https. There is already a warning like you suggest showing up on http:
![grafik](https://user-images.githubusercontent.com/25026204/71605066-73579680-2b66-11ea-921b-5bc7aca56367.png)
(from my local dev setup, running in Firefox)

If the connection is not secured with https any chromium-based browser will disable the crypto-api which is needed for this app to work.

**Comment by Tsaukpaetra** [comment]
Huh. Because I _did_ load it in http mode and did not see the result as shown, which lead me here. 🤷‍♀

**Comment by maurerle** [comment]
Which means, that you are using a browser which disables the Web Crypto API on unsecure connections. Like every Chromium-based browser does.
In this case the app can't operate and shows the `Your browser doesn't support some important features we're using.` error.
On other Browsers, like Firefox and current Edge, the functionality is not limited like that so it only shows the warning seen in my post.

**Comment by Tsaukpaetra** [comment]
What I'm saying is, instead of "This is impossible GO AWAY", it should provide the suggestion that perhaps the user should switch to HTTPS (something they probably want anyways), i.e.:

![image](https://user-images.githubusercontent.com/1989056/71616470-a2c0d000-2b73-11ea-879c-c913d2127830.png)

**Comment by maurerle** [comment]
This error does not only occur on chromium-based browsers, but on any with disabled/unsupported crypto API ([like old browsers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API#Browser_compatibility)), in which case switching to HTTPS won't help.

Besides that you can't know if HTTPS is available (for local network instances and dev setups probably not).
But if HTTPS is available then the webserver should be set up to redirect HTTP to HTTPS for your cloud which would make it impossible to see this message for chromium end users.

**Comment by Tsaukpaetra** [comment]
Obviously it's not impossible, for behold I am here.
But whatever, I'm not interested in arguing "should be" and "in an optimal world", I do that plenty enough elsewhere.
Good day to you.
