### ISSUE TITLE
Support providing custom config.json options

### ISSUE THREAD

**Issue by CoplandTech** [jhass/nextcloud-keeweb#119]
Hey. When installing KeeWeb, I encountered a problem where I need to create the config.json file
I tried to install it outside the keeweb directory on the path www/nextcloud/app-pkg. Also installed in keeweb/template.
When called in url/apps/keeweb/?config=config.json, the result: Redirects to the nextcloud home directory, when you go to url/apps/keeweb/keeweb/?config=config.json, the result: Invalid application URL.
There are no special errors in the browser console.

The config.json file is needed to specify the gID in Google Drive.

**Comment by jhass** [comment]
Sorry, this is confusing me quite a bit. Are you asking how to provide custom configuration options  to Keeweb?  That's how I interpreted your issue so far and rephrased the issue title to clarify that, please correct me if I'm wrong :)

In case you don't actually care about the Nextcloud integration, I recommend to host Keeweb independently or use https://app.keeweb.info. I'm not sure if this will ever be in scope of the addon.

**Comment by maurerle** [comment]
I think it would be very useful to give a consistent UX through Nextcloud, so the Locale (#79) and dark mode (#110) setting should match the user preferences as requested by other users.

I don't think we should provide the configuration as a config.json as keeweb does.
But in my opinion configuration should be in the scope of this add-on.

A first move into this direction is implemented in #122 .

**Comment by Cupcake911** [comment]
Is there an update on this? I would love to have the option to have a custom config.json.
