### ISSUE TITLE
Nexcloud 17 Support

### ISSUE THREAD

**Issue by hippie131** [jhass/nextcloud-keeweb#120]
Just got the notification to upgrade to Nextcloud 17 and keeweb is listed under "Apps missing updates". Will keeweb be updated to add support for Nextcloud 17?

**Comment by TitanSpirit** [comment]
This is actually the same KeeWeb version 0.5.1 since Nextcloud 11. 
@jhass please update your KeeWeeb for Nextcloud 17, so it can be recognized as safe app.
Your tool is great. Do not abandon it.

**Comment by jhass** [comment]
See the discussion in #115
