### ISSUE TITLE
with nextcloud installed from snap

### ISSUE THREAD

**Issue by guoguoguilai** [jhass/nextcloud-keeweb#125]
How to use keeweb with nextcloud installed from snap?
I just skip running`sudo -u www-data php occ files:scan --all` 
When I open .kdbx, it throws `KdbxError: Error NotImplemented: AES-CBC not implemented`
![image](https://user-images.githubusercontent.com/47267017/71018398-59b05b00-2133-11ea-927a-fab445ca93e9.png)
How to solve this?

**Comment by jhass** [comment]
This might be  due to not loading keeweb over HTTPS.
