### ISSUE TITLE
Plugin crashes after reboot inside docker container

### ISSUE THREAD

**Issue by jefferyyjhsu** [jhass/nextcloud-keeweb#131]
**Issues:**

- Plugin running inside a _linuxserver/nextcloud_ docker container will crash after every time host machine restarts.
![image](https://user-images.githubusercontent.com/14210265/74106983-a283ff00-4b39-11ea-89be-b4a08b9a1d1a.png)

- Restarting just the docker container will fix the issue.

**Version**

- Chrome: 79.0.3945.130
- linuxserver/nextcloud image: cd264ee39d2cc82f9bed6df45645cb1f8222ad7fc4fcd4138e07522a7829d0e3
- Nginx:1.16.1
- Nextcloud: 16.0.7.1
- Nextcloud-Keeweb: 0.6.1

**nextcloud.log**

> {"reqId":"hX3rnNlB542JrzNbpMTl","level":3,"time":"2020-02-10T01:27:35+08:00","remoteAddr":"192.168.0.3","user":"jeffery","app":"index","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FHSUHome_Encrypt%2Fjeffery%2FKeepass_Database","message":{"Exception":"Exception","Message":"Could not json_encode due to invalid non UTF-8 characters in the array: array (\n  'status' => 'success',\n  'data' => \n  array (\n    'uploadMaxFilesize' => INF,\n    'maxHumanFilesize' => 'Upload (max. INF PB)',\n    'freeSpace' => -2,\n    'quota' => -3,\n    'used' => 6958,\n    'usedSpacePercent' => 0,\n    'owner' => 'jeffery',\n    'ownerDisplayName' => 'Jeffery Hsu',\n  ),\n)","Code":0,"Trace":[{"file":"\/config\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":119,"function":"render","class":"OCP\\AppFramework\\Http\\JSONResponse","type":"->","args":[]},{"file":"\/config\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\AjaxController"},"getStorageStats"]},{"file":"\/config\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files\\Controller\\AjaxController","getStorageStats",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"files.ajax.getStorageStats"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"files.ajax.getStorageStats"}]},{"file":"\/config\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"files.ajax.getStorageStats"}]},{"file":"\/config\/www\/nextcloud\/lib\/base.php","line":972,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/files\/ajax\/getstoragestats.php"]},{"file":"\/config\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/config\/www\/nextcloud\/lib\/public\/AppFramework\/Http\/JSONResponse.php","Line":71,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.130 Safari\/537.36","version":"16.0.7.1"}

**nginx-error.log**

> 2020/02/10 01:27:45 [error] 347#347: *220 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.0.3, server: _, request: "GET /index.php/avatar/jeffery/32?v=0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.0.3"
2020/02/10 01:27:45 [error] 349#349: *221 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.0.3, server: _, request: "GET /index.php/apps/keeweb/keeweb?config=config?file=/HSUHome_Encrypt/jeffery/Keepass_Database/Keepass_Database.kdbx HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.0.3"
2020/02/10 01:27:45 [error] 347#347: *226 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.0.3, server: _, request: "GET /index.php/svg/core/logo/logo?color=fff&v=1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.0.3"
2020/02/10 01:27:46 [error] 348#348: *227 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.0.3, server: _, request: "GET /index.php/apps/accessibility/js/accessibility?v=0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.0.3"
2020/02/10 01:27:46 [error] 347#347: *226 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.0.3, server: _, request: "GET /index.php/apps/theming/js/theming?v=0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.0.3"
2020/02/10 01:27:49 [error] 348#348: *227 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.0.3, server: _, request: "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.0.3"

**php-error.log**

> [10-Feb-2020 01:27:45] WARNING: [pool www] child 438 exited on signal 11 (SIGSEGV) after 82.123423 seconds from start
[10-Feb-2020 01:27:45] NOTICE: [pool www] child 455 started
[10-Feb-2020 01:27:45] WARNING: [pool www] child 382 exited on signal 11 (SIGSEGV) after 930.958793 seconds from start
[10-Feb-2020 01:27:45] NOTICE: [pool www] child 456 started
[10-Feb-2020 01:27:45] WARNING: [pool www] child 431 exited on signal 11 (SIGSEGV) after 91.295150 seconds from start
[10-Feb-2020 01:27:45] NOTICE: [pool www] child 457 started
[10-Feb-2020 01:27:46] WARNING: [pool www] child 455 exited on signal 11 (SIGSEGV) after 0.656560 seconds from start
[10-Feb-2020 01:27:46] NOTICE: [pool www] child 458 started
[10-Feb-2020 01:27:46] WARNING: [pool www] child 456 exited on signal 11 (SIGSEGV) after 0.656711 seconds from start
[10-Feb-2020 01:27:46] NOTICE: [pool www] child 459 started
[10-Feb-2020 01:27:49] WARNING: [pool www] child 457 exited on signal 11 (SIGSEGV) after 3.739818 seconds from start
[10-Feb-2020 01:27:49] NOTICE: [pool www] child 460 started

**Comment by jhass** [comment]
I can't fathom how something we do here could be responsible for this. Given you log SIGSEGV it seems like something is corrupting memory. Either your RAM is physically bad or maybe you got some dependencies linked together that shouldn't be in their particular versions.

**Comment by jefferyyjhsu** [comment]
@jhass, 
Thanks for the quick feedback. I am sorry but I am quite new to Nextcloud and Nginx. If this doesn't seem like an issue with the plugin I will close the ticket.
