### ISSUE TITLE
Service Worker cannot registered

### ISSUE THREAD

**Issue by code-sport** [jhass/nextcloud-keeweb#132]
Actual I cannot open a KeePass file in the browser from the NextCloud (version 18.0.0).

In the console I got following error:
> Refused to create a worker from 'https://example.com/apps/keeweb/service-worker.js' because it violates the following Content Security Policy directive: "child-src blob:". Note that 'worker-src' was not explicitly set, so 'child-src' is used as a fallback.
> 
>2020-02-11T08:33:20.983Z [updater] Failed to register a service worker DOMException: Failed to register a ServiceWorker: The provided scriptURL ('https://example.com/apps/keeweb/service-worker.js') violates the Content Security Policy.

How can I solve this?

**Comment by Slug-V** [comment]
Reproduced in my 17.0.2 instance.
I put `$csp->addAllowedChildSrcDomain("'self'");` next to this line: https://github.com/jhass/nextcloud-keeweb/blob/e88088a7cea2dc7fa40a97a13541c88b00a6c6cb/keeweb/controller/pagecontroller.php#L116
and the error disappeared.
but Service Worker still didn't work and my Vivaldi got a new error: 
> Failed to register a service worker DOMException: Failed to register a ServiceWorker for scope ('https://example.com/index.php/apps/keeweb/') with script ('https://example.com/index.php/apps/keeweb/service-worker.js'): The script resource is behind a redirect, which is disallowed.

hmm. 

note: There is no "worker-src" in [Nextcloud Document](https://docs.nextcloud.com/server/18/developer_manual/app/requests/controllers.html).

**Comment by jhass** [comment]
Can you try the following build for me? [keeweb.tar.gz](https://github.com/jhass/nextcloud-keeweb/files/4190827/keeweb.tar.gz)

Changes are https://github.com/jhass/nextcloud-keeweb/commit/6a40a1504760a13fb22acea390ebdf5e67935ce0, there probably is a better way to do this but....

**Comment by Slug-V** [comment]
I applied this and got "[updater] Service worker registered", but it seems something went wrong.

related (consecutive) logs:
>(timestamp) [app] Started in 439ms ¯\_(ツ)_/¯

>service-worker.js:6 Refused to connect to 'https://example.com/index.php/apps/keeweb/?v=1.12.3' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
>
>(anonymous) @ service-worker.js:6
>Promise.then (async)
>(anonymous) @ service-worker.js:5

>keeweb?config=config:1 (timestamp) [updater] Service worker registered

>service-worker.js:6 Refused to connect to 'https://example.com/index.php/apps/keeweb/?v=1.12.3' because it violates the document's Content Security Policy.
>(anonymous) @ service-worker.js:6
>Promise.then (async)
>(anonymous) @ service-worker.js:5

>service-worker.js:6 Uncaught (in promise) TypeError: Failed to fetch
>    at service-worker.js:6

Both default-src and connect-src seems not mentioned in the document.
hmmm, is there a proper way using Service Worker [to offline access](https://github.com/keeweb/keeweb#self-hosting) in Nextcloud Apps?
If there isn't yet, a probably better way is that we keep this unimplemented until Nextcloud API provides it.

and another error seems unrelated to Service Worker:
>script.js?v=6c23cb4a-5:47 Uncaught ReferenceError: fileInfo is not defined
>    at script.js?v=6c23cb4a-5:47
 >   at script.js?v=6c23cb4a-5:55
>(anonymous) @ script.js?v=6c23cb4a-5:47
>(anonymous) @ script.js?v=6c23cb4a-5:55

**Comment by jhass** [comment]
> hmmm, is there a proper way using Service Worker to offline access in Nextcloud Apps?

Honestly, I have no clue.

You can try setting the CSP with
```diff
diff --git a/keeweb/controller/pagecontroller.php b/keeweb/controller/pagecontroller.php
index 2b171cc..c5bb5ea 100644
--- a/keeweb/controller/pagecontroller.php
+++ b/keeweb/controller/pagecontroller.php
@@ -110,6 +110,7 @@ class PageController extends Controller {
                $response = new DataDisplayResponse(file_get_contents(($this->appManager->getAppPath("keeweb").
                        "/templates/service-worker.js")));
                $response->addHeader("Content-Type", "application/javascript");
+               $response->setContentSecurityPolicy($this->getCSP());
                return $response;
        }
```

 and see how much further you come.

**Comment by Slug-V** [comment]
I wrote this and console errors(related to Service Worker) got away finally!
There will be some offline test is needed...**wait. Using nextcloud-keeweb offline?** No database available if keeweb works offline because we use WebDAV. Currently, we should download the database to use this feature. This usage has no difference with original KeeWeb🤣

And, @code-sport, you can use the tgz(note: take care that all data in this archive have "../" path) with this pagecontroller.php modify, but I don't think that this Service Worker fix helps your problem.
