### ISSUE TITLE
Once installed, the app displays code instead of the app itself

### ISSUE THREAD

**Issue by Cornoualis** [jhass/nextcloud-keeweb#133]
Hi,

I just installed keewab with the NextCloud app manager, and after installation, 
the app only displays code instead of the app.
Here's a [screenshot](https://ibb.co/CB6qr5D) of what I see.

Can you please help me? 

I can provide more information about my installation if you need, just ask me! ;-)

Thanks!

**Comment by jhass** [comment]
Well it obviously works for a lot of people, so  we gonna need a ton more details. What's your Nextcloud version? Browser and browser version? Which browser extensions do you have installed, especially of the content blocking kind (ad blockers, noscript etc.)? Is there any output to share on the browser error console?

**Comment by Cornoualis** [comment]
Right now, I'm on Firefox 73, with no extension activated, but I had the exact same result with different browsers (Brave, Chrome), on different devices (PC, Mac, Android Phone).
PHP version: 7.0

On the console side, I have this message:
`SyntaxError: '' literal not terminated before end of script keeweb:1:706777`

In the Nextcloud logs, I have this reccuring message:
`
{"reqId":"Pj8539w3CyoOE9L5hGZw","level":3,"time":"2020-02-18T14:31:47+00:00","remoteAddr":"136.173.62.144","user":"mat","app":"no app in context","method":"GET","url":"/nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications","message":{"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"ocs.provisioning_api.AppsController.disable\" as such route does not exist.","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":337,"function":"generate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->","args":["ocs.provisioning_api.AppsController.disable",{"app":"nextcloud_announcements"},1]},{"file":"/var/www/nextcloud/lib/private/Route/CachingRouter.php","line":60,"function":"generate","class":"OC\\Route\\Router","type":"->","args":["ocs.provisioning_api.AppsController.disable",{"app":"nextcloud_announcements"},false]},{"file":"/var/www/nextcloud/lib/private/URLGenerator.php","line":95,"function":"generate","class":"OC\\Route\\CachingRouter","type":"->","args":["ocs.provisioning_api.AppsController.disable",{"app":"nextcloud_announcements"},false]},{"file":"/var/www/nextcloud/apps/nextcloud_announcements/lib/Notification/Notifier.php","line":89,"function":"linkToOCSRouteAbsolute","class":"OC\\URLGenerator","type":"->","args":["provisioning_api.AppsController.disable",{"app":"nextcloud_announcements"}]},{"file":"/var/www/nextcloud/lib/private/Notification/Manager.php","line":226,"function":"prepare","class":"OCA\\NextcloudAnnouncements\\Notification\\Notifier","type":"->","args":[{"__class__":"OC\\Notification\\Notification"},"fr"]},{"file":"/var/www/nextcloud/apps/notifications/lib/Controller/EndpointController.php","line":92,"function":"prepare","class":"OC\\Notification\\Manager","type":"->","args":[{"__class__":"OC\\Notification\\Notification"},"fr"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":166,"function":"listNotifications","class":"OCA\\Notifications\\Controller\\EndpointController","type":"->","args":["v2"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Notifications\\Controller\\EndpointController"},"listNotifications"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Notifications\\Controller\\EndpointController"},"listNotifications"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Notifications\\Controller\\EndpointController","listNotifications",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"apiVersion":"v2","_route":"ocs.notifications.Endpoint.listNotifications"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"apiVersion":"v2","_route":"ocs.notifications.Endpoint.listNotifications"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"apiVersion":"v2","_route":"ocs.notifications.Endpoint.listNotifications"}]},{"file":"/var/www/nextcloud/ocs/v1.php","line":82,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/notifications/api/v2/notifications"]},{"file":"/var/www/nextcloud/ocs/v2.php","line":24,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/3rdparty/symfony/routing/Generator/UrlGenerator.php","Line":113,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/73.0","version":"15.0.12.1","id":"5e4bf553ede50"}
`

**Comment by jhass** [comment]
Well I  have no clue.  The nextcloud logs  seem irrelevant to the issue. You  didn't mention your Nextcloud  version yet :)  Also I think I would  just try removing and reinstalling the app,  maybe something went wrong while extracting  it.

**Comment by Cornoualis** [comment]
I'm on Nextcloud 15.0.14...maybe the problem comes from here.
I'm using Nextcloud on Yunohost, and it seems that they use a very old version of Nextcloud.

I think I should try to manually upgrade it.

**Comment by Cornoualis** [comment]
I think we can close this issue...sorry for disturbing and thanks for your help! ;-)
