### ISSUE TITLE
Keeweb  0.6.2 not work on Nextcloud 15.0.14

### ISSUE THREAD

**Issue by Gamoth** [jhass/nextcloud-keeweb#136]
Hello,
I just installed Nextcloud and I wanted to install keeweb.
If I try to click on the application keeweb, I get the following errors.
`'+d(typeof(r=null!=(r=s.name||(null!=t?t.name:t))?r:l)===c?r.call(o,{name:"name",hash:{},data:i}):r)+"
"+d((s.res||t&amp;&amp;t.res||l).call(o,"exportFileInfo",{name:"res",hash:{},data:i}))+"`

[https://framapic.org/4xHgfpSV0o4u/uCBRCcBB8GyN.png](https://framapic.org/4xHgfpSV0o4u/uCBRCcBB8GyN.png)

Here is my configuration :
PHP 7.0.33-0+deb9u7
Debian 9.12 64bit 

Kinds

**Comment by jhass** [comment]
Looks like we need to drop support for Nextcloud 15, already reported in #133

**Comment by Gamoth** [comment]
Hello,

I didn't see that the used version of Nextcloud was no longer supported.
It's not that old, though.
Should I assume that the ticket can be closed?

**Comment by jhass** [comment]
Our app info xml declaration still has 11  in it but just because nobody tested it against old versions and updated it accordingly.

**Comment by Gamoth** [comment]
Sorry I'm French, I don't quite understand the meaning of your previous sentence.

**Comment by euZebe** [comment]
I'm using Yunohost, which does not yet provide an easy way to upgrade to a more recent version of Nextcloud, so I'm stuck to Nextcloud 15.0.14.
Is there a way to downgrade keeweb ?

**Comment by maurerle** [comment]
I just set up an environment in docker running nextcloud:15 which runs PHP 7.3.14.
Its working fine there, so it seems that the PHP version (in both cases 7.0.x) is a problem for the upgrade of keeweb and not the nextcloud version.
(PHP 7.0 ist supported with NC15 but not anymore with any currently supported NC version, see [here](https://docs.nextcloud.com/server/15/admin_manual/installation/system_requirements.html)

@euZebe you can deinstall the app and follow the instructions from [here](https://github.com/jhass/nextcloud-keeweb#install) using the Version 0.5.1 to downgrade. But maybe upgrading PHP is also possible for you

**Comment by euZebe** [comment]
Thanks @maurerle ; it worked well!

@Gamoth if it can help, here are the steps I followed
```
cd /tmp
wget https://github.com/jhass/nextcloud-keeweb/releases/download/v0.5.1/keeweb-0.5.1.tar.gz
tar xvf keeweb-0.5.1.tar.gz -C /var/www/nextcloud/apps
```
then activate it in nextcloud.

**Comment by maurerle** [comment]
It would be good to deploy a final 0.5.1 for 11-15 and set the current minimum version to NC16 as it requires PHP 7.1 or higher which probably does not run into this issue.
(Maybe you can also just change the minimum version of the existing releases, i dont know about that)

**Comment by Gamoth** [comment]
@euZebe : Thanks, it works

**Comment by maurerle** [comment]
As we track this issue in the above mentioned issue, we can close this too?

**Comment by arnowelzel** [comment]
I also vote for setting the minimum version for Keeweb for Nextcloud 0.6.x to Nextcloud 16 as Nextcloud 17 is the oldest version which is still maintained and Nextcloud 16 already reached end of life in 2020-06.

Also see: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by jhass** [comment]
Sure, just do it.
