### ISSUE TITLE
ServiceWorker is caching too much.

### ISSUE THREAD

**Issue by HolgerHees** [jhass/nextcloud-keeweb#137]
Hi,

after I updated to your latest version 0.6.2 I found out that my previous fix https://github.com/jhass/nextcloud-keeweb/issues/36 is not working anymore. The reason is the new service worker implementation. I guess your intention is to cache the 1.3MB big main file.

But currently it caches everything. The biggest problem is that it caches also the index page which contains dynamic data like the request token. That means, once it is cached it will never update the request token anymore which results in invalid tokens when you visit the app the second time. It still load the old file with the old outdated token which is embedded in the "data-requesttoken" attribute of the "head" tag.

Another side effect is that it caches also style files etc. Means if you update your layout or anything else outside of keebweb it will also never updated.

Another issues I found is that the service worker javascript file is missing in github so I'm not able to create a pull request.

That's why I post my changes here

```
const VERSION = '1.12.3';

self.addEventListener('install', event =>
    event.waitUntil(
        caches.open('v1').then(cache =>
            fetch('.?v=' + VERSION).then(response => {
                if (response.ok) {
                    return cache.put('.', response);
                }
            })
        )
    )
);

self.addEventListener('fetch', event => {
    if( event.request.url.indexOf("keeweb?config") == -1 )
    {   
        event.respondWith(
            fetch(event.request)
        );
    }
    else
    {
        event.respondWith(
            caches.match(event.request.url).then(response => response || fetch(event.request))
        );
    }
});
```

**Comment by maurerle** [comment]
FYI currently nextcloud-keeweb gets build by first cloning the keeweb repository (which holds the source of the [service-worker.js](https://github.com/keeweb/keeweb/blob/master/app/service-worker.js) and then applying needed patches to keeweb like in 

https://github.com/jhass/nextcloud-keeweb/blob/d7ed6f301e1984afc87f2f5b98815cfd58d835ea/bin/build#L25

so you can add a patch file for your change and the `git apply patch` line in the build script if you want to create a PR for your changes.

**Comment by HolgerHees** [comment]
ahh, the service worker comes from the original keeweb.

the problem is that the patch is more or less specific for the nextcloud / keeweb combination. I'm not sure if they accept it as a generic patch.

**Comment by maurerle** [comment]
Can be closed as merged
