### ISSUE TITLE
possible Bug: Error opening file No Last-Modified header

### ISSUE THREAD

**Issue by thomas-mc-work** [jhass/nextcloud-keeweb#145]
I think this problem came with the upgrade from Nextcloud 18.0.x to 18.0.4.

Steps:

- click on a kdbx file in files app
- keeweb is opening as expected and asking for password
- When I confirm the password/keyfile, then I get a popup saying:

```
Error opening file
No Last-Modified header
```

This was working as expected before the latest upgrade. There haven't been any changes to the apache webserver configuration in that time.

**Comment by maurerle** [comment]
This message comes from Keeweb and not from keeweb nextcloud. You can find further information here:
https://github.com/keeweb/keeweb/issues/511

Tldr: you should make sure that the Last Modified header exists.
I hope this help!

**Comment by thomas-mc-work** [comment]
**Update:** I could narrow down the restriction: This only applies to files within in a shared folder.

**Comment by maurerle** [comment]
Is the shared folder part of external storage or federated?
It wouldn't make sense if your NC server just does not provide the Last-modified header on shared links.

I just checked and on my instance sharing and opening keepass files with other nextcloud users is working.

**Comment by thomas-mc-work** [comment]
No. It's on the same machine without any external storage.

> I just checked and on my instance sharing and opening keepass files with other nextcloud users is working.

Strange. Did you share the file or the containing folder?

**Comment by maurerle** [comment]
I checked both and both is working. I use nginx and nextcloud-fpm-docker.

**Comment by thomas-mc-work** [comment]
Have you got an idea how to debug this situation?

**Comment by thomas-mc-work** [comment]
When you request that file via WebDAV, does your server provide the Last-Modified header in the response?

**Comment by maurerle** [comment]
I just checked and I have one. You can test for it with `curl -H "GET" --head http://username:password@example.org/remote.php/webdav/Passwords.kdbx`.
So there must be something wrong with your apache configuration.

Maybe you can add the Last-Modified Header manually in your reverse proxy or need to enable some caching setting?
Using ETag would also be a solution (which is also provided by my configuration and the default nc19 docker image)

**Comment by thomas-mc-work** [comment]
I was able to track that further down track down: The name of the share contains a leading `#`. When I removed it only form the target then it works just fine! Also I found out that using a `+` as prefix it leads to another error: `file not found`.

Maybe someone could try to reproduce that behaviour? That would make it possible to exclude the Apache configuration as the source of the problem. After that I think I would address this issue to the Nextcloud server team. What do you think?

**Comment by maurerle** [comment]
Great that you could find the root of the error. I could reproduce both.

Gladly this issue has been resolved by #141 . I just tested it in my test-environment and can confirm that the error does not occur with this patch.

**Comment by thomas-mc-work** [comment]
Marvellous!

It would be great to see a release containing this fix soon ❤

**Comment by jhass** [comment]
See https://github.com/jhass/nextcloud-keeweb/pull/148#issuecomment-651213826

**Comment by maurerle** [comment]
I think this issue can be closed
