### ISSUE TITLE
Update for Nextcloud 19

### ISSUE THREAD

**Issue by AlNotSteve** [jhass/nextcloud-keeweb#146]
Hi,

KeeWeb is marked as untested in the NC19 app store.  Can you update to NC19?

I've tested briefly KeeWeb in NC19 and it appears to work fine.

**Comment by MorgothRB** [comment]
There's also a PR for NC19 back end compatibility: #148

**Comment by leolivier** [comment]
And now nextcloud 20...

**Comment by arnowelzel** [comment]
This will be solved with #154 and the PR for #148 will also be included.
