### ISSUE TITLE
can someone help me use keeweb within nextcloud

### ISSUE THREAD

**Issue by vincentkenny01** [jhass/nextcloud-keeweb#149]
hello,
I am noob when it comes to keeweb. I can install and enable the keeweb app within nextcloud but I do not know how to use it from thereon. I have searched in vain for a user guide but I did not come across anything. My use case is to have full control on the database and be able to access my password on the go from a mobile phone, pc etc. 

Can someone please point on how to use this?

**Comment by maurerle** [comment]
The best workflow to access your KeePass file on a phone is using something like KeePassDX (which also works offline).
You currently can't create a new Keepass file from within Nextcloud so you need a client app and sync the *.kdbx file through Nextcloud.
Then you can add passwords with Keeweb by just clicking on the *.kdbx File from the Nextcloud UI in a browser.

Keeweb is only for usage in a browser. I use it for clients which I do not own and need to access a PW. On my own devices I use a client application and sync changes to the *.kdbx through Nextcloud.

You might want to look into the NC passwords app which saves the passwords encrypted in the database and does not need a extra *.kdbx file and master password (and is therefore probably more user-friendly for beginners).

**Comment by Timoses** [comment]
Since I haven't found appropriate documentation of the full features of this app, I'll pose my question here as well:
My initial thought was that this app would allow me to open a Keepass file which is stored under 'Files' within Nextcloud. Only then I realized that upon selecting 'Open' it would ask me to select a file from my computer's local storage (not from the Nextcloud Files).

Would WebDav be the way to achieve above scenario? Why do I have to use WebDav even though I'm already logged into my Nextcloud Account?

**Comment by arnowelzel** [comment]
> Since I haven't found appropriate documentation of the full features of this app, I'll pose my question here as well:
> My initial thought was that this app would allow me to open a Keepass file which is stored under 'Files' within Nextcloud. Only then I realized that upon selecting 'Open' it would ask me to select a file from my computer's local storage (not from the Nextcloud Files).
> 
> Would WebDav be the way to achieve above scenario? Why do I have to use WebDav even though I'm already logged into my Nextcloud Account?

This is not the way how this app works. The idea is, that you create a kdbx file using Keepass on another device and then move it to your Nextcloud server. There you just open it by clicking on it in the files app in the browser - then it will be opened with Keeweb.

I think, we should remove the Keeweb icon in the tool bar completely, so people don't get the wrong idea how to use this app. It makes no sense to open Keeweb this way anyway.

**Comment by Timoses** [comment]
> This is not the way how this app works. The idea is, that you create a kdbx file using Keepass on another device and then move it to your Nextcloud server. There you just open it by clicking on it in the files app in the browser - then it will be opened with Keeweb.

Thanks, that input was very helpful! : )

On the architecture side: Is decryption done server-side or client-side (in-browser) when typing in the keepass kdbx password? (It could be very helpful to have an **Architecture** section in the README describing *keeweb*'s approach.)
