### ISSUE TITLE
Clear local storage on nextcloud sign out 

### ISSUE THREAD

**Issue by dmenzel** [jhass/nextcloud-keeweb#15]
I just found out, that if user A opens a keepass file and user B (who does not have access to A's file) opens the keepass app, he sees A's file as last opened and can even open it if he/she has the password.

I consider this to be quite a security problem.

**Comment by jhass** [comment]
Well, the database is decrypted and  stored in the browser. If you share the same browser session between two users that shouldn't see anything of each other, isn't this your least problem?

**Comment by maurerle** [comment]
I have the patch #139 applied and the filename is not remembered after sign-out and sign-in with different user. So can be closed too.
