### ISSUE TITLE
Unable to open *.kdbx file with space in path

### ISSUE THREAD

**Issue by eack** [jhass/nextcloud-keeweb#153]
When I try to open a *.kdbx file which has a space in the path the file could not be found.

The path is cutted at the first occurence of a space.

**Comment by b90g** [comment]
Maybe fixed by: https://github.com/jhass/nextcloud-keeweb/pull/141 ?

**Comment by maurerle** [comment]
Probably. We should really release the latest master I think

**Comment by maurerle** [comment]
This is fixed with 0.6.3-beta
