### ISSUE TITLE
Update to latest version of Keeweb an prepare release for Nextcloud 19

### ISSUE THREAD

**Issue by arnowelzel** [jhass/nextcloud-keeweb#154]
The current version in the Nextcloud app store (https://apps.nextcloud.com/apps/keeweb) is only compatible up to Nextcloud 18. However since Nextcloud 19 is already released a new version of Keeweb for Nextcloud is required. This should also include an update to the latest version of Keeweb.

This includes:

- [x] Use latest version of Keeweb and check the existing patches which are applied to make Keeweb usable within Nextcloud
- [x] Test in all supported versions of Nextcloud

To discuss:

At the moment Keeweb 0.6.2 supports Nextcloud 11-19. However according to https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule all version of Nextcloud before 17 are already "end-of-life". So it might make things much easier just to concentrate on the versions of Nextcloud which are still maintained (17, 18, 19).

**Comment by arnowelzel** [comment]
Since I can't find the reason for the service worker error I just removed the server worker registration in the Keeweb updater. As far I tested this, it works fine even without the service worker. Any idea why the service worker would be needed?

**Comment by jhass** [comment]
I think it's supposed to cache the  app? That is it's a supplement or replacement for the app manifest thingy.

**Comment by arnowelzel** [comment]
Version 1.15 of Keeweb is about 1.5 MB. Even if this would have to be loaded with every start of the app, I think we can omit caching here.

The use case for Keeweb are not mobile devices (there you can use Keepass2Android etc.) but laptops and desktop machines - and those usually have a decent internet connection so it should not be a problem. Using gzip compression on the web server brings the volume down to about 500 KB. Using a 16 MBit/s connection this takes less than 0.3 seconds to load.

**Comment by arnowelzel** [comment]
Since we now have a version which contains everything needed for NC19 I will do some more testing with different Nextcloud versions and let you know when a new release can be prepared. Everything else should go into a future update.

**Comment by maurerle** [comment]
For a better possibility of testing we could release the 0.6.3 version here on github, so that people can extract it easily and help testing. 
This would enlarge the testing pool a lot.
Then we can release it to the store if no bugs are reported.

We could release it as unstable to the store too until we are sure it does not break anything (Like https://apps.nextcloud.com/apps/calendar).

**Comment by arnowelzel** [comment]
If you are interested in testing I can provide a ZIP archive with the version I've build.

**Comment by maurerle** [comment]
Would be great!

**Comment by arnowelzel** [comment]
You can find a ZIP archive of the BETA version here: https://nextcloud.0x0c.de/s/RSaD77MfAPjSsSA

**Comment by maurerle** [comment]
Thanks!
If anyone else wants to help testing the new release:

```
cd /tmp
wget -O nextcloud-keeweb.zip https://nextcloud.0x0c.de/s/RSaD77MfAPjSsSA/download
sudo unzip nextcloud-keeweb.zip -d /var/www/html/apps/
rm nextcloud-keeweb.zip
```

**Comment by maurerle** [comment]
What I tested:
Different Browsers: Firefox, ungoogled-chromium and Edge
Downloading kdbx, opening file, editing entries and saving
Spacebar or special characters in Name

Install on NC18, Upgrade on NC19

Works fine, except for incognito mode (which did not work before either) and MS Edge but those are upstream problems.

**Comment by abc2006** [comment]
Just installed on Nextcloud 19.0.3
can't confirm that it breaks Activity view.
Also no problems with Incognito mode or Edge. (Maybe i've tested the wrong functions?) 
For me, everything is fine.
Win10, Ubuntu 20, Android 10
Firefox, chrome, Edge, Inkognito

Thank you for this great App!

**Comment by arnowelzel** [comment]
I have tested the app with NC 17, 18 and 19 and could not find any major issues. I'd recommend releasing it.

**Comment by ezzra** [comment]
so its released an available NC 19 now?

**Comment by jhass** [comment]
Yes.
