### ISSUE TITLE
Keeweb using http instead of https when accessing webdav

### ISSUE THREAD

**Issue by lkerck** [jhass/nextcloud-keeweb#155]
Even though my nextcloud is using https for everything, keeweb tries to use http and errors out after I enter the kdbx password.
Is there some way to tell keeweb to use https when accessing the kdbx over webdav?

**Comment by lkerck** [comment]
The Server serves https and redirects http to https.
The problem seems to be Nextclouds CSP, which has "connect-src: 'self' " set and therefore blocks the http request (tested in Firefox 79 and Chrome 84).
Can I get Keeweb to use https by default or do I have to somehow modify the CSP?

**Comment by arnowelzel** [comment]
Normally Keeweb should use exactly the the protocol of your Nextcloud server and on my own server this works fine. I open a file from the file browser and Keeweb will just open it as expected.

When you open the Keeweb app itself you should see the last file which was opened with it below the password input:

![grafik](https://user-images.githubusercontent.com/6613614/90990695-bb1ea880-e5a3-11ea-961d-c40a9ecdd93b.png)

When you hover this entry with the mouse you should see the full URL as tooltip. Does this also report "http://" or does it start with "https://"?

**Comment by lkerck** [comment]
The URL tooltip shows http even though nextcloud is opened with https.

**Comment by arnowelzel** [comment]
Please do the following:

- clear all browser caches.
- login to your Nextcloud instance.
- open the web developer console of your browser and select the "network" tab so you can see which http requests get send to the server and what responses it gets.
- now open a kdbx file in the Nextcloud file manager and check what requests get send. You should see something like `https://yourserver.example/apps/keeweb/?open=/yourfile.kdbx` (if you have the kdbx file in a folder, this will show up here as will - e.g. `https://yourserver.example/apps/keeweb/?open=/somefolder/yourfile.kdbx`

Is this the case?

**Comment by lkerck** [comment]
Yes, thats right. The request goes over https and looks exactly like described.
<details>
  <summary>Request details</summary>

```
GET https://cloud.****.**/apps/keeweb/?open=/****/****.kdbx
{"GET":{"scheme":"https","host":"cloud.****.**","filename":"/apps/keeweb/","query":{"open":"/****/****.kdbx"}}}

HTTP/1.1 200 OK
Date: Mon, 24 Aug 2020 09:32:52 GMT
Server: Apache
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: none
X-XSS-Protection: 1; mode=block
X-Powered-By: PHP/7.4.8
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Content-Security-Policy: default-src 'none';base-uri 'none';manifest-src 'self';script-src 'self' https://plugins.keeweb.info 'unsafe-inline' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob: https://favicon.keeweb.info;font-src 'self' data:;connect-src 'self' https://plugins.keeweb.info;frame-src 'self' 'unsafe-inline' 'unsafe-eval' blob:;child-src blob: 'self'
Feature-Policy: autoplay 'self';camera 'none';fullscreen 'self';geolocation 'none';microphone 'none';payment 'none'
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 6729
Content-Type: text/html; charset=UTF-8
Keep-Alive: timeout=15, max=79
Connection: Keep-Alive
```


</details>

**Comment by arnowelzel** [comment]
And even then Keeweb uses http and not https? This is really strange - I have no clue at all why.

**Comment by jhass** [comment]
I guess somehow nextcloud is not recognizing that it's being accessed via HTTPS. You may want to double check that whatever terminates your TLS connection sets `X-Forwarded-Proto: https`. If that doesn't help you may try https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html?highlight=overwriteprotocol#overwrite-parameters

**Comment by lkerck** [comment]
Perfect, 'overwriteprotocol' => 'https' in the nextcloud config.php did the trick.

Thank you for your help.
