### ISSUE TITLE
keeweb.php is missing

### ISSUE THREAD

**Issue by xn--nding-jua** [jhass/nextcloud-keeweb#16]
Within the gitignore-file the keeweb.php has been added. This results in an "Internal Server Error" as the file keeweb.php is missing within the folder "templates".

Please remove this file from gitignore-file and upload it. Otherwise the app is not working.

kind regards,
Chris

**Comment by xn--nding-jua** [comment]
Grmp. Downloading the "release" tar.gz solved this. Sorry.

**Comment by jhass** [comment]
Yes, it's built by a script and I see no reason to bloat the repo with it. The dev setup instructions in the README will build it.
