### ISSUE TITLE
Keeweb blank page

### ISSUE THREAD

**Issue by Peachy74** [jhass/nextcloud-keeweb#161]
After installing keeweb version 0.6.3, I click on a .kdbx but the page remains empty. Nextcloud 19.0.3 knows that the kdbc should be opened with the keeweb.

My PHP version:
  php -v
PHP 7.3.22-1 + ubuntu18.04.1 + deb.sury.org + 1 (cli) (built: Sep 9 2020 06:46:30) (NTS)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.22, Copyright (c) 1998-2018 Zend Technologies
     with Zend OPcache v7.3.22-1 + ubuntu18.04.1 + deb.sury.org + 1, Copyright (c) 1999-2018, by Zend Technologies

How can I isolate the error?

regards
Alex

**Comment by jhass** [comment]
The error log from the browser console would be interesting.

**Comment by Peachy74** [comment]
what do these lines mean to me:

[Error] Unrecognized Content-Security-Policy directive 'worker-src'.

[Error] Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' does not appear in the style-src directive of the Content Security Policy. (keeweb, line 2)
[Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (keeweb, line 2)

**Comment by jhass** [comment]
What browser in what version do you use?

**Comment by Peachy74** [comment]
now I try it with firefox 81.0 and I get this hint:
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src").

The lines in the previous post were generated with Safari 14.0

**Comment by jhass** [comment]
Is your webserver (apache, nginx) maybe configured to enforce a particular CSP?

**Comment by Peachy74** [comment]
I use Apache2. Where could I find such an attitude?

**Comment by arnowelzel** [comment]
Look for any Header directives in the configuration of the website similar to this:

```
Header set Content-Secure-Policy "default-src 'self';"
```

Also check the response headers of the server, if there is any `Content-Secure-Policy` header part of the response.

**Comment by Peachy74** [comment]
Thanks for the hint.
I don't think there is anything.:

```
/etc/apache2# grep "Content" */*
conf-available/security.conf:#Header set X-Content-Type-Options: "nosniff"
conf-enabled/security.conf:#Header set X-Content-Type-Options: "nosniff"
```

**Comment by jhass** [comment]
Well then I'm out of clues. The app sets the CSP accordingly: https://github.com/jhass/nextcloud-keeweb/blob/master/keeweb/controller/pagecontroller.php#L134

**Comment by arnowelzel** [comment]
Maybe this is relevant here: https://github.com/keeweb/keeweb/commit/cd0a25f9106be6a70312d7c5d391259460a693c0

Since we use release-1.15 and not v1.15.7 it may be worth a try. I can prepare a test version based on v1.15.7 just to see if this changes anything.

**Comment by arnowelzel** [comment]
There is a new beta version 0.6.4 you can check out: https://nextcloud.0x0c.de/s/jjZgiwGr5bGcc2r

I did a test with NC 18 and NC 19 and could not find any major issues.

Extract the archive and replace the existing apps/keeweb folder in your Nextcloud server with the one in the archive. After this you need to run the Nextcloud updater once.

**Comment by TomGem** [comment]
I have the same problem on NC 18.0.9, today I updated to Keeweb 0.6.3.
Since then there is just a blank page. The console says:

> [Error] Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' does not appear in the style-src directive of the Content Security Policy. (keeweb, line 1)
> [Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (keeweb, line 1, x3)

Furthermore I just installed the 0.6.4 beta version @arnowelzel posted 2 hours ago, the problem persists.

**Comment by dieideeistgut** [comment]
FYI: I can second this with my 19.0.3 installation and Keeweb 0.6.3 as well as Keeweb 0.6.4beta. Downgrading Keeweb to 0.6.2. fixes the blank-screen for my installation. [ It's traeffik routed and dockerized ].

**Comment by TomGem** [comment]
Same here, Keeweb 0.6.2 works, on a conventional LAMP setup.

**Comment by arnowelzel** [comment]
Well - since it works perfectly fine on my Nextcloud 19.0.3 on Linux with Apache 2.4 and PHP-FPM 7.4 I have no idea where to start searching. Is it possible to get a Nextcloud login to one of the machines on which it does not work so I can check what exactly is going on?

**Comment by arnowelzel** [comment]
Thanks to @dieideeistgut I could investigate the issue a bit further - it seems to be a browser specific problem.

I can use Keeweb on the very server of @dieideeistgut with Firefox, Chrome, Vivaldi and Edge without any issue - but I have Linux and Windows. @dieideeistgut mentioned, that the error only occurs with Chrome and Safari on macOS.

Anyone else reporting this issue: Please also add the exact browser and operating system version you use.

**Comment by arnowelzel** [comment]
Ok, after fiddling around a bit more - I give up! The errors tell about missing CSPs which are in fact set and we can't do anything else then to set the CSPs. Just have a look at the response header of <yourserver>/apps/keeweb/keeweb?config=config.

Furthermore:

After having a look at https://github.com/jhass/nextcloud-keeweb/blob/master/keeweb/controller/pagecontroller.php#L121-L144 and checking https://content-security-policy.com/unsafe-inline/ I would even consider the app unsafe for production use.

Sorry for the bad news - but an honest judgement of the situation helps more than promises.

**Comment by arnowelzel** [comment]
In the next days I will try to figure out, if there is any chance at all to get Keeweb running in the intended way - using a service worker and proper CSPs. However - I'm not sure yet, if this is possible at all.

**Comment by jstark1** [comment]
Same Issue here with NC 19 and Keeweb 0.6.3. I can raise the Issue is only in Safari (on Mac) and Apple IOS Devices. In Firefox and Chrom works as assumed. Safari reports: 

[Error] Unrecognized Content-Security-Policy directive 'worker-src'.
[Error] Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' does not appear in the style-src directive of the Content Security Policy. (keeweb, line 1)
[Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (keeweb, line 1, x3)

i suspect a problem with the CSP Level 3 and Safari. 
The Check https://content-security-policy.com/browser-test/ with Safari Reports "CSP Level 3 Inline Hash Not Supported"

**Comment by esmail** [comment]
Just wanted to confirm that I'm seeing the same console errors in iOS (14.2) Safari:
```
[Error] Unrecognized Content-Security-Policy directive 'worker-src'.

[Error] Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' does not appear in the style-src directive of the Content Security Policy. (keeweb, line 1)
[Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (keeweb, line 1, x3)```

**Comment by arnowelzel** [comment]
Please check, if https://app.keeweb.info/ has the same problems. If yes, this is an upstream problem which has to be fixed there.

**Comment by jstark1** [comment]
https://app.keeweb.info/ does not have this Problem. It throws only the first Errorline and the Page loads successful.

[Error] Unrecognized Content-Security-Policy directive 'worker-src'.
[Info] 2020-12-02T07:48:38.018Z [start-profiler] App started in 168ms: fetching=13ms, pre-init=71ms, loading modules=42ms, document ready=7ms, creating app model=3ms, loading configs=1ms, initializing modules=1ms, loading remote config=1ms, checking features=0ms, initializing storage=1ms, first view rendering=40ms, app ready event=1ms (app.keeweb.info, line 1)
[Info] 2020-12-02T07:48:38.041Z [updater] Service worker registered (app.keeweb.info, line 1)

**Comment by arnowelzel** [comment]
Unfortunately I don't have a mac or iPhone and no Safari - so no chance to fix this as I don't know how to test that.

**Comment by jstark1** [comment]
When I remove the Header
`<meta http-equiv="Content-Security-Policy" ...>`
from keeweb/templates/keeweb.php the Page loads in Safari on MacOS and IOS. 

I see still a content-security-policy Header in the http reply, but it works.

**Comment by jhass** [comment]
Ah, we probably should just `sed` this out then, as the controller is setting a CSP via the headers already.

**Comment by jstark1** [comment]
sounds like plan. i vote for it

**Comment by copos77** [comment]
> When I remove the Header
> `<meta http-equiv="Content-Security-Policy" ...>`
> from keeweb/templates/keeweb.php the Page loads in Safari on MacOS and IOS.
> 
> I see still a content-security-policy Header in the http reply, but it works.

works like a charm :-)

**Comment by esmail** [comment]
FYI, in Docker (`nextcloud:19-fpm`) I couldn't seem to get the edited version recognized by mounting it to `/var/www/html/custom_apps/keeweb` folder so I had to use the normal `/var/www/html/apps/keeweb` instead (and don't forget that the owner needs to be `www-data`)

**Comment by jstark1** [comment]
I use the Docker image nextcloud:20-apache. My modified Version is mounted to /var/www/html/custom_apps/keeweb/templates/keeweb.php without any problems.

**Comment by arnowelzel** [comment]
@jstark1 I just created a new version based on Keeweb 1.16.3 and with the patch applied as mentioned in #163 and removed CSP in Keeweb itself.

If you want to test it: https://nextcloud.0x0c.de/s/Tit29WBmdRMFYzF

**Comment by arnowelzel** [comment]
The new version is now released (0.6.4) including the proposed fix for Safari. You can please check, if the problem is still present? Thank you!

**Comment by jstark1** [comment]
Commit 16833bb works as expected. From my point of view, the bug can be closed. Thanks @arnowelzel for the fix.

**Comment by eewingt** [comment]
i am still having this issue, see the attached image. Any help is appreciated.
![keeweberror](https://github.com/jhass/nextcloud-keeweb/assets/89181023/d7af5670-d78e-46ef-999b-f4896061f2bb)
