### ISSUE TITLE
Nextcloud wants to download my database instead of opening it - depending on user

### ISSUE THREAD

**Issue by abc2006** [jhass/nextcloud-keeweb#164]
Hi, 
while it looks like an duplicate of #116, 
my problem is a bit larger: 

I have a NC19 on Ubuntu 20 up and running. 
I am the administrator of the server.
I installed KeeWeb in my (Administrator) Account.
I can click on my database and it gets opened/asking for password.
So the software actually does work.

My Wife also has an account on this server. In order to access the same Database, i created a Group folder and shared it (with me and my wife, as its possible to create server-wide Group-folders that are not bound to any specific user)
She has full access, everything fine.

Third i created another user, lets name him John Wayne, with a simpler password, so i can access my keepass-database without remembering an terribly complex password. This seems safe to me because: 
The Database itself has an really good password
John Wayne is not allowed to create or delete any files
John Wayne has no space left on his account (Group-Folder limited to 20MB, User-Account limited to 1B)
Problem: 
if i log in as John Wayne and try to open the Database, i get it offered to download.
If i start KeeWeb (icon in the left upper corner next to activity) it runs fine and lets me open files from my computer, but no files from John Waynes Account.
If i add John Wayne to the Administrator-Group, he is able to open the Database, like my personal account.
If i grant John Wayne create or delete rights, behaviour does not change.

Do you have any idea how to fix this problem? 
I was totally fine with opening the Database read-only (as i was able to grab my account-password and open the Database there for write access. 
Write-Access in John Waynes Account was also nice, but not necessary.

I hope this is enough information for an overview, as i am not that familiar with nextcloud.
If you need any more information, please ask and i will try to provide these.
Thank you very much in advance, 
abc2006

**Comment by abc2006** [comment]
I have to correct me: it's the Write-Permission in the Group-Folder: 

![grafik](https://user-images.githubusercontent.com/2698681/95354341-974dc280-08c4-11eb-9e9c-610d8b53521c.png)

With Write-Permission it works fine. Now i have to check if sb can overwrite my file with this permission.
Anyway, read-only-access was a nice feature, if possible.

**Comment by abc2006** [comment]
okay, dug into the Groupware-Plugin, looks like a Problem over there.
Sorry for disturbing

**Comment by arnowelzel** [comment]
JFTR:

The group folders plugin adds logic to Nextcloud which does not work well in some situations.

It's better if you share folders instead of using "group folders". Maybe you just create a "family admin user" with which you create the folder you both need and then share the folder with your login and the one of your wife. That's how I do this, since this is the natual way how Nextcloud works and the share does not depend on either if your logins then.

**Comment by abc2006** [comment]
Too Bad, i was happy to have this "logic" finally. Okay, as its the only point at the moment, i'll give it another try. Next issue, it gets changed back. 
Thanks for your hint!

**Comment by arnowelzel** [comment]
You may give it another try by using `occ files:scan -all` command after enabling the plugin. Also see https://docs.nextcloud.com/server/19/admin_manual/configuration_server/occ_command.html#scan
