### ISSUE TITLE
Support for kdbx 4 format

### ISSUE THREAD

**Issue by poggenpower** [jhass/nextcloud-keeweb#166]
Seems i am not able to open kdbx files in version 4 format at least not with the new encryption algorithm.  

Would be great if keeweb would support the latest format and security features. 

If not possible a documentation about the supported formats would be helpful. 
Anf may be a better error message then “wrong xml root” if opening an unsupported kdbx file. 

Thanks for your great work in keeweb sofar

**Comment by jhass** [comment]
Please verify this reproduces at https://app.keeweb.info/ and then open the issue at https://github.com/keeweb/keeweb, if not existing already.

If it does work on https://app.keeweb.info we can reopen this to look into why it wouldn't work inside nextcloud.
