### ISSUE TITLE
Multi-User / Collaborative Editing

### ISSUE THREAD

**Issue by nemhods** [jhass/nextcloud-keeweb#167]
When editing a file in a shared folder in Nextcloud, multiple users may write conflicting changes into the same Keeweb file.

Collaborative editing of kdbx files would be amazing, but for starters, a more simple .lock file may suffice. 

The KeePass App also supports this with a workaround where it checks for file changes immediately before saving, and then offers to sync data before saving (but that would be a feature that would have to be implemented in keeweb itself).

**Comment by arnowelzel** [comment]
Keeweb for Nextcloud uses the code of the Keeweb App - so it works there as well.

When you click the "Sync" button, the database in Keeweb will be synced with the version on Nextcloud and changes from an updated version there will be merged.
