### ISSUE TITLE
Yubikey integration

### ISSUE THREAD

**Issue by tilllt** [jhass/nextcloud-keeweb#171]
I saw that the standalone keeweb has Yubikey 2FA integration, while the nextcloud version does not seem to have it. Is this something that is not possible to implement or just a matter of time? Since I am using my keeweb with a Yubikey I couldn't use the Nextcloud plugin but it would be really handy if this was possible...

**Comment by arnowelzel** [comment]
Is Yubikey 2FA also possible with https://app.keeweb.info/? If not I assume, this requires some native interfaces to the operating system which are not available within a website.

**Comment by tilllt** [comment]
Ok, I checked it, you are right, it's not implemented in the web app, but for reasons that are not valid. There was a security bug in 2018 that has long been fixed. So it would just be a matter of disabling it on certain versions of chrome.

**Comment by arnowelzel** [comment]
Anyway - if there is no official way to use it, we can't provide it. The Nextcloud integration is mostly a version of the web app for Nextcloud.

**Comment by tilllt** [comment]
Well, with my limited understanding of the reason given by the author of keeweb, it's technically no problem to implement it. It had been disabled for security concerns which don't apply anymore. But I will take this issue to the keeweb repo. Thanks for the feedback.
