### ISSUE TITLE
nextcloud-keeweb vs app.keeweb.info usage?

### ISSUE THREAD

**Issue by ace-at-git** [jhass/nextcloud-keeweb#176]
Hello nextcloud-keeweb-team,

first of all the nextcloud-keeweb plugin works on my nextcloud installation as expected - good software!

My question is more directed towards the intended usage of app.keeweb.info in combination of the nextcloud/nextcloud-keeweb plugin. Since I am new to keeweb and password safes I would like to understand if I am going in the right direction or if I miss something...

My understanding is, that when I use the nextcloud-keeweb plugin I can only use the stored passwords with working internet and working nextcloud server. Therefor I wanted to use app.keeweb.info via webdav on various computers and sync the *.kdbx file to the browser cache with just one click. I hope that I can access this without internet or working nextcloud once it is synced!?

Unfortunately I could not test this hypothesis, because I could not use the app.keepas.info with my nextcould, nginx, revers-proxy and I was not able to fix the access to the *.kdbx file. It centers around CORS settings, but all I read so far did not help me. But that is another story...

I start to think that I miss something more obvious or my use case assumptions are wrong. I would appreciate if someone could point me to the right direction or appropriate documentation!

How do you get around the need to install keypass apps on all machines (browser is already installed) that should use the *.kdbx file without messing around with local copies of the *.kdbx file when internet/nextcloud is off?

Kind regards

Bernd

**Comment by dodedodo** [comment]
@ace-at-git  

Keepass consists of a database file(.kdbx), and a client. Keeweb is one such client, but you are not limited to keeweb. The vanilla keepass.info client and KeepassXC are 2 notable desktop competitors. 

If you want to access your passwords database offline, I'd recommend installing the nextcloud sync app (which syncs files locally like dropbox). Once synced, you can open your database with any application you want.

**Comment by arnowelzel** [comment]
Without a local copy of the database you can't access the data.

This can be done using a Nextcloud client which synchronizes the data or you use app.keeweb.info which stores the data in the DOM storage in the browser itself. In any case a local copy is needed.
