### ISSUE TITLE
Nextcloud 21 compatibility

### ISSUE THREAD

**Issue by Derkades** [jhass/nextcloud-keeweb#178]

**Comment by arnowelzel** [comment]
Any known issues with Nextcloud 21 when you force installation on it?

**Comment by Derkades** [comment]
I have not tried upgrading and force-enabling it yet because I only run one "production" nextcloud instance. I may try spinning up a second one.

**Comment by arnowelzel** [comment]
Nevermind - I have a development version here as well which I just did not switch to the beta channel yet.

I'll update that to 21.0.0 RC2 and check if there are any problems.

**Comment by arnowelzel** [comment]
A quick test did not show any problems. I could download and activate Keeweb despite it's not marked as compatible yet. Also the MIME type registration for `*.kdbx`, opening a file and syncing changes back to Nextcloud worked without any problem.

**Comment by arnowelzel** [comment]
Closed with dbf7051185a03af03c7bae57bf2fe1c0a18ba3b8
