### ISSUE TITLE
URL to internal Database

### ISSUE THREAD

**Issue by AtlanGon** [jhass/nextcloud-keeweb#182]
I'm using the internal DB on my Nextcloud server (in a Docker Container). 
I tried different Android apps for my phone, but for those I need the URL to the kdbx file.
I can't find it in the container and the URL is also not shown anywhere. I don't want to use a file in the files storage.

Thanks

**Comment by arnowelzel** [comment]
This is the same as for every other file in your Nextcloud. You need to use WebDAV. Also see https://docs.nextcloud.com/server/latest/user_manual/en/files/access_webdav.html.

The format of the URL would be: `https://<SERVER>/remote.php/dav/files/<USER>/<FILENAME>`
or: `https://<SERVER>/remote.php/dav/files/<USER>/<PATH/.../<FILENAME>`

For example if your server is `https://my.example.com` and your username `atlangon` and the KeePass file is named `database.kdbx` in the folder `passwords`, this would be:

`https://my.example.com/remote.php/dav/files/atlangon/passwords/database.kdbx`

If you don't use a subfolder in Nextcloud, this would be:

`https://my.example.com/remote.php/dav/files/atlangon/database.kdbx`

**Comment by AtlanGon** [comment]
I'm aware of that.

My problem is, the DB is not a file in https://my.example.com/remote.php/webdav/ like database.kdbx or /passwords/database.kdbx
I get those files easily.

My DB is in the internal storage of keeweb.
![grafik](https://user-images.githubusercontent.com/83112050/115954953-0fdc3f80-a4f4-11eb-93c5-fa8c7414d716.png)

**Comment by arnowelzel** [comment]
The internal storage of Keeweb is only the storage of your browser. There is no URL to it.
