### ISSUE TITLE
Nextcloud 22 Support

### ISSUE THREAD

**Issue by sunjam** [jhass/nextcloud-keeweb#185]
Just released.  Thanks for considering!

**Comment by arnowelzel** [comment]
Thanks for the reminder. I'll take care of it.

**Comment by Kalimeiro** [comment]
Please update the plugin, we have 1.16.7 but now Keeweb has release 1.18.6

Thanks for all.

**Comment by thinkofher** [comment]
@Kalimeiro check out patch from #186 :)

**Comment by arnowelzel** [comment]
Closed with #186 and b3c213ce7f70ed59cb0735a8d448db4eb202c1b0
