### ISSUE TITLE
Keepass fails to open file edited from nextcloud-keeweb

### ISSUE THREAD

**Issue by alxrdn** [jhass/nextcloud-keeweb#194]
Hi,
not sure if the problem comes from nextcloud-keeweb or upstream keeweb (or even keepass)...

I have a setup where I access my kdbx file which is served by my nextcloud from both
- nextcloud-keeweb
- Keepass2Android on my mobile through webdav
- keepass on my desktop thanks to Nextcloud sync client

It was all working just fine until recently.

Since a few days, if I edit my kdbx file from within nextcloud-keeweb, then when I try to open it from either keepass desktop or Keepass2Android I get the same error message :
> Failed to load the specified file!
> The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.

Sorry I am not able to pinpoint the exact change (ie apps updates) that broke the whole setup since I do not edit my kdbx file frequently...
The current versions I use are the latest:
- nextcloud-keeweb 0.6.8 onNextcloud 22.2.3
- Keepass2Android 1.09b-r1 on my mobile through webdav
- keepass 2.49 on my desktop thanks to Nextcloud sync client

Does that ring any bell to anyone ?
Many thanks

**Comment by arnowelzel** [comment]
Sorry - no idea what is wrong here. The only hint about this I found is https://github.com/Kunzisoft/KeePassDX/issues/708.

I use [KeepassXC  2.6.6](https://keepassxc.org) on the desktop with the synced file locally and Keepass2Android 1.00a-r3 with direct access using WebDAV and never had this problem so far. Maybe you give KeepassXC a try for the desktop

**Comment by alxrdn** [comment]
I managed to pin down the cause : it seems that nextcloud-keeweb now (?) saves by default in KDBX4 format, in that case I can not open the saved file with KeePass 2.49 on my Windows desktop.
When I change the format in nextcloud-keeweb to KDBX3 and save again, then the file can be opened with KeePass.

**Comment by alxrdn** [comment]
may it be related to https://github.com/keeweb/keeweb/issues/1598 ?

**Comment by arnowelzel** [comment]
We use v1.18.7.

Since this is not a problem we can fix, I will close this now.
