### ISSUE TITLE
How to restore a password in trashbin?

### ISSUE THREAD

**Issue by saschabrockel** [jhass/nextcloud-keeweb#198]
Hey there it's a simple question but I can't find a solution for it. I accidentally deleted a password and just want to restore it from the trash bin but the only button I see is to delete it completely. And I don't want to type it in manually in the normal passwords again...

Am I missing something?

**Comment by maurerle** [comment]
Hi,
you can simply drag and drop the entry from the trashbin back to the folder you deleted it from

You can even drag entries to the trashbin in the lower left to delete them.
Or move items around by dragging them.

Have a nice day!

**Comment by saschabrockel** [comment]
![image](https://user-images.githubusercontent.com/33376463/155252394-aa0d33db-1281-4c9d-9e8d-ddf0a4e789c4.png)
Ehm not working for me. I am in the trashbin and if I drag an element the browser shows me the prohibition sign anywhere I drag it.

**Comment by arnowelzel** [comment]
Works fine for me.

Just keep in mind that you have to select either the kdbx file itself as drop target or one of the folders.

**Comment by saschabrockel** [comment]
Now it also works. No idea why. I tried the same thing before as you did @arnowelzel. But still, you helped. Thank you.
