### ISSUE TITLE
Default search term

### ISSUE THREAD

**Issue by caco3** [jhass/nextcloud-keeweb#20]
When I open the app, the search box is filled with my username. This makes it to find no entries since I use different usernames on other services.

Why is the search box pre-filled?
I would suggest to keep it empty.

![spectacle c16103](https://cloud.githubusercontent.com/assets/1783586/18411847/eb82f598-7780-11e6-836f-547cbb4df926.png)

**Comment by jhass** [comment]
This doesn't happen for me, perhaps it's your browsers saved credentials feature going rogue?

**Comment by caco3** [comment]
Indeed, it seems only to happen in Firefox. No clue why, because why should it prefill my username in a searchbox.
