### ISSUE TITLE
Add NC24 compatibility

### ISSUE THREAD

**Issue by xkill** [jhass/nextcloud-keeweb#200]
Please, add NC24 compatibility

**Comment by LarsBel** [comment]
Workaround:

edit /apps/keeweb/appinfo/info.xml and set max-version="25"

**Comment by tobiaseigen** [comment]
Thanks! Does this mean there is no incompatibility issue between keeweb and version 24?

**Comment by arnowelzel** [comment]
Unfortunately I did not have time yet to update the basic application structure and Keeweb still uses some deprecated things (also see https://github.com/jhass/nextcloud-keeweb/issues/195). However Keeweb should still work in NC 24 as well. I hope to get the next major update finished within the next weeks.

**Comment by tobiaseigen** [comment]
Thanks! Really appreciate your work here. Having keepass in nextcloud is very, very valuable. I updated using LarsBel suggestion and it appears to be working, for now.

**Comment by arnowelzel** [comment]
Closed with https://github.com/jhass/nextcloud-keeweb/pull/201/commits/e3e10ba96e82fa867f573a6d6553fe68659a1d73

**Comment by arnowelzel** [comment]
Unfortunatley, Keeweb can not be built any longer. The latest version is v1.18.7 from July 2021. This version now produces errors when building.

**Comment by arnowelzel** [comment]
It seems, the project is dead, until there is a new maintainer:

https://github.com/keeweb/keeweb/issues/2022

**Comment by tobiaseigen** [comment]
Bummer! I really hope someone takes up the project because it's important. Keeweb is the best way to keep moving forward with .kdbx password safe files, stored locally or on nextcloud. And I really value it as an open source software project. 

Thanks for your work making keeweb work so nicely in nextcloud, hitherto. Much appreciated! 🤗

**Comment by arnowelzel** [comment]
Fortunately at least the build could be fixed and there is now a new version which supports NC 24 as well.

However the major issue remains - KeeWeb itself needs a new maintainer. I also posted this to https://help.nextcloud.com/t/help-keeweb-upstream-needs-a-new-maintainer/139045
