### ISSUE TITLE
/appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.

### ISSUE THREAD

**Issue by hardwareadictos** [jhass/nextcloud-keeweb#205]
I just have this spamming on my Nextcloud logs regarding to keeweb app:

![image](https://user-images.githubusercontent.com/20403906/168765274-242993e7-0dc1-43dd-8eeb-e98123c1b315.png)

Thanks in advance :)

**Comment by arnowelzel** [comment]
To be more specific:

In `config/config.php` of your Nextcloud installation make sure that the loglevel is set to 2:

```
  'loglevel' => 2,
```

Also see https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html.

Level 2 is also the default level for new installations and means "log warnings, errors and fatal error". Having also debug messages in the log is no recommended on production systems as this fills up the log quite fast.

**Comment by arnowelzel** [comment]
Unfortunately due to very limited time a was not able to work on a fix for that - any help is welcome. But as explained in https://github.com/jhass/nextcloud-keeweb/issues/221 already, I'm not sure about the future of this project.

**Comment by arnowelzel** [comment]
Closed by #223
