### ISSUE TITLE
Cannot download favicon for URLs

### ISSUE THREAD

**Issue by saschabrockel** [jhass/nextcloud-keeweb#208]
If I want to download a favicon for any URL in some entry I'll get:

`Refused to load the image 'https://services.keeweb.info/favicon/mein.ionos.de' because it violates the following Content Security Policy directive: "img-src 'self' data: blob: https://favicon.keeweb.info".`

And it is also telling:

```
keeweb?config=config?file=%2FSingh.kdbx:1 2022-08-17T02:39:35.837Z [icon-select-view] Favicon download error: https://services.keeweb.info/favicon/mein.ionos.de Event {isTrusted: true, type: 'error', target: img, currentTarget: img, eventPhase: 2, …}
r.error @ keeweb?config=config?file=%2FSingh.kdbx:1
t.onerror @ keeweb?config=config?file=%2FSingh.kdbx:1
error (async)
downloadIcon @ keeweb?config=config?file=%2FSingh.kdbx:1
eventListener @ keeweb?config=config?file=%2FSingh.kdbx:1
e @ keeweb?config=config?file=%2FSingh.kdbx:1
```

It never worked. Does anybody have an idea how to fix this?

**Comment by arnowelzel** [comment]
What exactly is the context of this? What to you mean with "download a favicon for any URL"?

**Comment by saschabrockel** [comment]
@arnowelzel the function exists also if you use https://app.keeweb.info/.

If you press this button here it should download the favicon from the website if it is available:
![image](https://user-images.githubusercontent.com/33376463/185245441-188e1de9-0885-44f7-8d7e-20698926b235.png)

So you say it is a CORS problem? How to fix it for a Nextcloud instance then?

**Comment by Slug-V** [comment]
I tried to reproduce the issue and got a CORS error about `https://services.keeweb.info/favicon/(entry URL)`.

I put `https://favicon.keeweb.info` as img-src in 3151df3, but I found this URL was [changed 2020](https://github.com/keeweb/keeweb/commit/00d7ff660468c4f2f1f25a757db1b998abd86cec).
I'll make another PR, which replaces the URL _, and change doublequote to singlequote which violates [Nextcloud coding guideline](https://docs.nextcloud.com/server/latest/developer_manual/getting_started/codingguidelines.html#coding)_.

**Comment by Slug-V** [comment]
Successfully downloaded on another PC.
Okay, it'll be caching issue. making PR.

**Comment by saschabrockel** [comment]
@Slug-V it seems to be broken again but I think it is an error of the main app of keeweb because app.keeweb.info doesn't work either for me. Same for you?

**Comment by Slug-V** [comment]
Mostly same.
No response from nextcloud-keeweb, won't use from app.keeweb.info(but devtools says it's a CORS issue), and cannot use if you directly access `https://services.keeweb.info/favicon/{domainname}` via browser.


> app.keeweb.info doesn't work

it has an extremely slow loading, but worked for me.

**Comment by arnowelzel** [comment]
For me it does not work on app.keeweb.info either and I don't know how to fix that anyway and the upstream KeeWeb is not maintained any longer (also see #221). So sorry, I can not do anything about this.
