### ISSUE TITLE
Compatibility with Nextcloud 25

### ISSUE THREAD

**Issue by cetcondor** [jhass/nextcloud-keeweb#209]
Keeweb is officially not compatible with the upcoming Nextcloud 25. Please publish an updated version.
[Thanks for your work]

**Comment by rafiwui** [comment]
Workaround mentioned in #200 does still work. There are no breaking changes in the [app maintenance guide](https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_25.html) from Nextcloud.

Workaround:
Edit `/apps/keeweb/appinfo/info.xml` and change
```
<dependencies>
    <nextcloud min-version="16" max-version="24" />
</dependencies>
```
to
```
<dependencies>
    <nextcloud min-version="16" max-version="25" />
</dependencies>
```

**Comment by arnowelzel** [comment]
Unfortunately due to the fact, that KeeWeb itself is not maintained any longer so far and the current build fails, I am not able to publish an update, sorry :-(

So this seems to be the end of Keeweb for Nextcloud.

**Comment by rafiwui** [comment]
But as long as a working KeeWeb version is available it should be possible to maintain and update the NC plugin or am I wrong?
Changes on the NC side would mostly break the integration not the KeeWeb itself, right?

**Comment by arnowelzel** [comment]
Unfortunately it seems that KeeWeb itself can no longer be built. I already asked @jhass for assistance with the GitHub publishing job, but at the moment it just doesn't work any longer. There are also a number of outdated components in KeeWeb where some already have critical security issues.
