### ISSUE TITLE
Trying to open it via webDAV results in "401 CSRF check not passed."

### ISSUE THREAD

**Issue by blubbsy** [jhass/nextcloud-keeweb#21]
Dear developers,

iam trying to work with keeweb with my nextcloud installation, but iam no table to open the database over webdav (same server). I always get an 401 error in the WebUI, and in the logs it says "401 CSRF check not passed."

Iam using nextcloud 10.0.1
nginx 1.10.1 with php7.0-fpm with enabled memcached

`{"reqId":"GjhRzB+e0ss5UsYoqNpn","remoteAddr":"62.218.23.122","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 CSRF check not passed.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/xxx.de\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php(155): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/xxx.de\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(163): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/xxx.de\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/xxx.de\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#5 \\\/var\\\/www\\\/xxx.de\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/xxx.de\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/xxx.de\\\/nextcloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/aleman...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/xxx.de\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php\",\"Line\":220,\"User\":\"yyy\"}","level":0,"time":"2016-10-12T07:22:18+00:00","method":"HEAD","url":"\/remote.php\/webdav\/KWdatabase.kdbx","user":"yyy"}
`

**Comment by jhass** [comment]
Did you install this plugin or did you just try to open a database stored in Nextcloud via WebDAV using the desktop version of Keeweb?

**Comment by sweaver19** [comment]
I'm having the same problem.  I installed version 0.2.9 of the KeeWeb Nextcloud app from here https://apps.nextcloud.com/apps/keeweb and am trying to open a kdbx file via WebDAV.  Nextcloud version is 10.0.1

**Comment by tflidd** [comment]
You can exclude the CSFR checks for a specific user agent:
https://help.nextcloud.com/t/nc11-webdav-for-keeweb/6481/9

However, it would be great to fix the CSFR issue here.

**Comment by LuCu11** [comment]
for the desktop Application, the solution is to paste  
// KeeWeb client
'/KeeWeb\/\d[.]\d[.]\d/',
in "incompatibleUserAgents" of the base.php (folder [path to nextcloud]/lib) 
like:
$incompatibleUserAgents = [
                        // OS X Finder
                        '/^WebDAVFS/',
                        //Windows Explorer
                        '/^Microsoft-WebDAV-MiniRedir/',
                        // KeeWeb client
                        '/KeeWeb\/\d[.]\d[.]\d/',
                ];

does anyone know the string vor the nextcloud-app on keeweb?

**Comment by LuCu11** [comment]
has anyone a solution for me?

**Comment by LuCu11** [comment]
I solved the problem, as I reinstalled nextcloud in version 11.0.2 and the issue is gone :-)
no matter why, but it works for me

**Comment by jhass** [comment]
Nobody here ever answered my initial question, so closing.
