### ISSUE TITLE
Kein Zugang mehr zu KeePass-Datei nach update durch keeweb

### ISSUE THREAD

**Issue by RalfWW** [jhass/nextcloud-keeweb#218]
Hallo,

ich nutze keeweb 0.6.12 unter Nextcloud 23.08. mit Nextcloud Desktop-Client 3.8.0 unter Windows 10

Nach einer Änderung in Nextcloud wird die .kdbx in Richtung Windows synchronisiert.

Dort kann ich diese dann nicht mehr mit KeePass 2,53,1 (64 bit) öffnen. 
Nach der - korrekten - Eingabe der PassPhrase erscheint die Fehlermeldung:

C:\...\meine.kdbx
Die ausgewählte Datei kann nicht geladen werden!
Die Eingabe ist keine gültige Base-64-Zeichnfolge, da sie ein Nicht-Base-64-Zeichen, mehr als zwei Leerstellen oder in den Leerstellen ein Zeichen enthält, das üngültig ist.
---
Ja, mehr als 2 Leerzeichen trifft zu, aber:
Nach der Wiederherstellung der .kdbx aus dem Backup, klappt auch der Zugang - wie seit Jahren - mit der PassPhrase.

Diese lässt sich erneut - nach dem Sync zu Nextcloud - auch dort mit keeweb öffnen.
Mache ich erneut eine Änderung, speichere diese per "Lock" in keeweb, kann ich die Datei unter Windows erneut, mit gleicher Fehlermeldung, nicht öffnen.

Das lässt sich also bei mir nachvollziehen!?

Gruß

Ralf

**Comment by arnowelzel** [comment]
Das Problem ist, dass KeeWeb selbst keine Updates mehr bekommt. Siehe auch: https://github.com/keeweb/keeweb/issues/2022

D.h. selbst wenn KeeWeb hier ein Problem hat, ist niemand in der Lage, das zu beheben. KeeWeb für Nextcloud nutzt auch nur KeeWeb als Downstream, d.h. es wird nur die vorhandene Version von KeeWeb eingebunden.

Allerdings sehe ich mit KeePassXC unter Windows keine Probleme - hier kann ich problemlos auch die Datei in Nextcloud ändern und weiterhin unter Windows öffnen. Eventuell wäre das eine Alternative. Siehe https://keepassxc.org

**Comment by RalfWW** [comment]
Besten Dank für den Hinweis auf KeePassXC.

Ich kann bestätigen, dass es mit KeePassXC unter

- Windows 10

- Ubuntu

- und KeePass2Android Offline

keine Probleme in Verbindung mit KeeWeb gibt.


Am 06.04.23 um 09:50 schrieb Arno Welzel:
