### ISSUE TITLE
Upgraded Nexcloud and Keeweb doesn't work?

### ISSUE THREAD

**Issue by notaduck** [jhass/nextcloud-keeweb#22]
Hi. I upgraded Nextcloud to 10.0.1 and reinstalled keeweb but I can't seem to find it under Nextclouds webinterface?

**Comment by agentdr8** [comment]
You may need to re-enable it after the upgrade. 
`php ./occ app:enable keeweb`
From your nextcloud directory.

**Comment by jhass** [comment]
It works as it should for me on 10.0.1 for me. @notaduck did @agentdr8's suggestion help you?

**Comment by notaduck** [comment]
So sry I forgot all about this issue! and i am so embarrassed......
Permissions issues was the solution
