### ISSUE TITLE
0.6.13 throws "Could not resolve OCA\\Keeweb\\Controller\\PageController"

### ISSUE THREAD

**Issue by mwllgr** [jhass/nextcloud-keeweb#224]
Hello,

I updated yesterday and now KeeWeb doesn't work for me (Nextcloud 26.0.2.1, PHP 8.2) anymore. Is anything known about it yet?

```
{
   "reqId":"xxxxxxxxxxxxxxxx",
   "level":3,
   "time":"2023-06-20T10:01:52+00:00",
   "remoteAddr":"xxx.xxx.xxx.xxx",
   "user":"xxxxxx",
   "app":"index",
   "method":"GET",
   "url":"/apps/keeweb/",
   "message":"Could not resolve OCA\\Keeweb\\Controller\\PageController! Class \"OCA\\Keeweb\\Controller\\PageController\" does not exist",
   "userAgent":"Mozilla/5.0 (xxxxxxx) Gecko/20100101 Firefox/112.0",
   "version":"26.0.2.1",
   "exception":{
      "Exception":"OC\\AppFramework\\Utility\\QueryNotFoundException",
      "Message":"Could not resolve OCA\\Keeweb\\Controller\\PageController! Class \"OCA\\Keeweb\\Controller\\PageController\" does not exist",
      "Code":0,
      "Trace":[
         {
            "file":"nc_root/lib/private/AppFramework/Utility/SimpleContainer.php",
            "line":142,
            "function":"resolve",
            "class":"OC\\AppFramework\\Utility\\SimpleContainer",
            "type":"->"
         },
         {
            "file":"nc_root/lib/private/AppFramework/DependencyInjection/DIContainer.php",
            "line":493,
            "function":"query",
            "class":"OC\\AppFramework\\Utility\\SimpleContainer",
            "type":"->"
         },
         {
            "file":"nc_root/lib/private/AppFramework/DependencyInjection/DIContainer.php",
            "line":465,
            "function":"queryNoFallback",
            "class":"OC\\AppFramework\\DependencyInjection\\DIContainer",
            "type":"->"
         },
         {
            "file":"nc_root/lib/private/AppFramework/App.php",
            "line":162,
            "function":"query",
            "class":"OC\\AppFramework\\DependencyInjection\\DIContainer",
            "type":"->"
         },
         {
            "file":"nc_root/lib/private/Route/Router.php",
            "line":315,
            "function":"main",
            "class":"OC\\AppFramework\\App",
            "type":"::"
         },
         {
            "file":"nc_root/lib/base.php",
            "line":1058,
            "function":"match",
            "class":"OC\\Route\\Router",
            "type":"->"
         },
         {
            "file":"nc_root/index.php",
            "line":36,
            "function":"handleRequest",
            "class":"OC",
            "type":"::"
         }
      ],
      "File":"nc_root/lib/private/AppFramework/Utility/SimpleContainer.php",
      "Line":131,
      "CustomMessage":"--"
   }
}
```

**Comment by arnowelzel** [comment]
We needed to update Keepass to stay compatible with Nextcloud 27 since the way how classes are loaded was changed.

However it seems that update now made it incompatible with Nextcloud 26 :-(

So either you upgrade to Nextcloud 27 or you manually downgrade Keeweb to Version 0.6.12. To downgrade:

1. Download https://github.com/jhass/nextcloud-keeweb/releases/download/v0.6.12/keeweb-0.6.12.tar.gz
2. Extract the contents
3. Replace the folder app/keeweb on your Nextcloud installation with the folder keeweb from that archive.

@burned42 Maybe you can also give it a try with NC26? Thanks!

**Comment by mwllgr** [comment]
Will try that, thanks. Maybe you could change the min-version in the appinfo xml so that this won't happen to other users?

**Comment by arnowelzel** [comment]
The problem is, that the version is already published and can not be changed back. I can only publish a new version 0.6.14 which contains the old code and a version 0.6.15 for NC 27 and above.

**Comment by arnowelzel** [comment]
According to https://github.com/jhass/nextcloud-keeweb/issues/219#issuecomment-1598528587 someone had the same issue and could fix this by restarting PHP-FPM. Maybe the OPCache still has old versions loaded because file validation was disabled or set to a very long interval.

**Comment by mwllgr** [comment]
Oh funny - that's it, works, thank you! You may close the issue ^^

**Comment by arnowelzel** [comment]
> Oh funny - that's it, works, thank you! You may close the issue ^^

Thanks for the feedback.

**Comment by burned42** [comment]
https://github.com/nextcloud/server/issues/38797 may be related, also mentioning a caching issue due to recent changes in nextcloud itself.
