### ISSUE TITLE
KW doesn't save last opened files

### ISSUE THREAD

**Issue by Fred-DTV** [jhass/nextcloud-keeweb#227]
Hi,

Unfortunately our Keeweb doesn't remember the last open files and doesn't offer a list to choose DBs from.

Is this a bug or am I missing a setting?

**Comment by arnowelzel** [comment]
No this is not a bug. It works as expected. The supposed way to use the app is to open the KDBX file in the Nextcloud files app. Only the last opened file will be remembered.

**Comment by arnowelzel** [comment]
Sorry, but even that is "works as expected". KeeWeb is not maintained any longer and this can not be fixed, sorry.
