### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by taschenlampe** [jhass/nextcloud-keeweb#229]
Hi!

When opening keeweb in NC28RC, I got an internal server error.

This should be the relevant log:

`{"reqId":"TaQzngMHMg5YWUCpkleC","level":3,"time":"2023-12-09T16:46:54+01:00","remoteAddr":"10.20.0.2","user":"xxx",
"app":"index","method":"GET","url":"/apps/keeweb/","message":"Call to undefined method OCP\\AppFramework\\Http\\EmptyCo
ntentSecurityPolicy::allowInlineScript() in file '/var/www/nextcloud/apps/keeweb/lib/Controller/PageController.php' lin
e 143","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0","version":"28.0.0.8","excep
tion":{"Exception":"Exception","Message":"Call to undefined method OCP\\AppFramework\\Http\\EmptyContentSecurityPolicy:
:allowInlineScript() in file '/var/www/nextcloud/apps/keeweb/lib/Controller/PageController.php' line 143","Code":0,"Tra
ce":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFra
mework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":
"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1069,"function":"m
atch","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleReque
st","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":169,"Pre
vious":{"Exception":"Error","Message":"Call to undefined method OCP\\AppFramework\\Http\\EmptyContentSecurityPolicy::al
lowInlineScript()","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/keeweb/lib/Controller/PageController.php","line":
56,"function":"getCSP","class":"OCA\\Keeweb\\Controller\\PageController","type":"->"},{"file":"/var/www/nextcloud/lib/p
rivate/AppFramework/Http/Dispatcher.php","line":230,"function":"index","class":"OCA\\Keeweb\\Controller\\PageController
","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"execute
Controller","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramew
ork/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/w
ww/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework

\\App","type":"::"},{"
file":"/var/www/nextcloud/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file"
:"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcl
oud/apps/keeweb/lib/Controller/PageController.php","Line":143},"message":"Call to undefined method OCP\\AppFramework\\H
ttp\\EmptyContentSecurityPolicy::allowInlineScript() in file '/var/www/nextcloud/apps/keeweb/lib/Controller/PageControl
ler.php' line 143","exception":{},"CustomMessage":"Call to undefined method OCP\\AppFramework\\Http\\EmptyContentSecuri
tyPolicy::allowInlineScript() in file '/var/www/nextcloud/apps/keeweb/lib/Controller/PageController.php' line 143"}}`

Additional Info:

**Desktop (please complete the following information):**
 - OS: OpenSuse TW
 - Browser: Firefox
 - Version: 120

**Server (please complete the following information):**
 - OS: ubuntu 22.04
 - HTTP server: nginx version: nginx/1.25.3
 - Database: mysql  Ver 15.1 Distrib 10.6.12-MariaDB
 - PHP version: Copyright (c) The PHP Group/Zend Engine v4.1.25, Copyright (c) Zend Technologies   with Zend OPcache v8.1.25, Copyright (c), by Zend Technologies
 - Nextcloud version: 28RC
 - Bookmarks app version: 13.1.1
 - Activated Nextcloud Apps: Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - bookmarks: 13.1.1
  - breezedark: 27.0.0
  - bruteforcesettings: 2.8.0
  - calendar: 4.6.0
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.0-rc.2
  - contactsinteraction: 1.9.0
  - cospend: 1.5.12
  - dashboard: 7.8.0
  - dav: 1.29.1
  - deck: 1.12.0-beta.4
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - integration_openai: 1.1.5
  - keeweb: 0.6.13
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - music: 1.9.1
  - news: 25.0.0-alpha2
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recognize: 6.0.1
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.0-beta.1
  - richdocumentscode: 23.5.602
  - serverinfo: 1.18.0
  - settings: 1.10.0
  - sharebymail: 1.18.0
  - spreed: 18.0.0-rc.3
  - support: 1.11.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - audioplayer: 3.4.0 (installed 3.4.0)
  - circles: 28.0.0-dev (installed 25.0.0)
  - documentserver_community: 0.1.13 (installed 0.1.13)
  - encryption: 2.16.0
  - files_external: 1.20.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - firstrunwizard: 2.17.0 (installed 2.9.0)
  - libresign: 7.1.1 (installed 7.1.1)
  - survey_client: 1.16.0 (installed 1.8.0)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - unsplash: 2.2.1 (installed 2.2.1)
  - user_ldap: 1.19.0
  - workflow_pdf_converter: 1.12.0 (installed 1.12.0)
 - Nextcloud configuration: 
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "vmd64337.contaboserver.net",
            "luckyshadows.net",
            "power.ddnss.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.0.8",
        "overwrite.cli.url": "https:\/\/vmd64337.contaboserver.net",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "activity_expire_days": 14,
        "auth.bruteforce.protection.enabled": true,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "filesystem_check_changes": 0,
        "filelocking.enabled": "true",
        "htaccess.RewriteBase": "\/",
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "log_rotate_size": 104857600,
        "logfile": "\/daten\/nextcloud.log",
        "logtimezone": "Europe\/Berlin",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "quota_include_external_storage": false,
        "share_folder": "\/Freigaben",
        "skeletondirectory": "",
        "trashbin_retention_obligation": "auto, 7",
        "app_install_overwrite": [
            "keeweb",
            "deck",
            "spreed",
            "bookmarks",
            "music",
            "unsplash",
            "onlyoffice",
            "breezedark",
            "documentserver_community",
            "bruteforcesettings",
            "news",
            "riotchat"
        ],
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "beta",
        "default_phone_region": "DE",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

**Web server error log**
```
nothing relevant (afaik)
```

Please advice, what information you/we might need to solve this issue, happy to help.

**Comment by arnowelzel** [comment]
Nextcloud 28 is not tested yet.

There is nothing you can do - KeeWeb needs to be changed to support Nextcloud 28 as well. So far I can only recommend sticking with Nextcloud 27 until KeeWeb is also updated for Nextcloud 28.

**Comment by arnowelzel** [comment]
It seems, Nextcloud 28 removed `OCP\\AppFramework\\Http\\EmptyContentSecurityPolicy::allowInlineScript()`. But without that, KeeWeb can not be used.

However, https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_28.html does not contain any hint what to use instead.

So if no one else has an idea how to fix this, KeeWeb will not work in Nextcloud 28 or newer any longer, sorry.

Since the upstream of KeeWeb is also not maintained any longer, I consider this app as "dead" (also see https://github.com/jhass/nextcloud-keeweb/issues/204 and https://github.com/jhass/nextcloud-keeweb/issues/221

**Comment by taschenlampe** [comment]
0.6.14 fixes the mentioned issue.
Thanks!
