### ISSUE TITLE
Incompatibility of KeyWeb App with Nextcloud 28 prevents upgrade of KeyCloud

### ISSUE THREAD

**Issue by gseilheimer** [jhass/nextcloud-keeweb#230]
**Issue Description:**
I am encountering an issue with the KeyWeb app in the context of the latest Nextcloud 28 update. It appears that KeyWeb has not been updated to be compatible with Nextcloud 28, which is preventing the upgrade of our KeyCloud instance.

**Technical Details:**
Nextcloud Version: 28
KeyWeb App Version: latest
Reproduction Steps:
Attempt to upgrade KeyCloud to the latest version.
Observe the compatibility issue with KeyWeb.
Expected Behavior:
The expectation is that KeyWeb should seamlessly integrate with Nextcloud 28, allowing for a smooth upgrade process of KeyCloud.

**Actual Behavior:**
The upgrade process is halted due to the incompatibility issue.

**Possible Solutions/Questions:**
Is there an ongoing effort to update KeyWeb for Nextcloud 28 compatibility?
Are there any known workarounds to address this issue temporarily?
Any assistance or insights from the community or developers would be greatly appreciated.
Thank you in advance for your support and looking forward to a resolution that enables us to upgrade to Nextcloud 28 without any further issues.

**Comment by arnowelzel** [comment]
See https://github.com/jhass/nextcloud-keeweb/issues/229 and https://github.com/jhass/nextcloud-keeweb/issues/204

Sorry, but I consider KeeWeb for Nextcloud as "dead" until anyone can help with further development.

**Comment by arnowelzel** [comment]
> OK. Then I'll uninstall the extension. Can the app simply be deactivated in the Nextcloud Marketplace when the project is finished?

The app is only supported up to Nextcloud 27 anyway. There is no need to deactivate it as you can not install it for Nextcloud 28 without telling Nexrtcloud to use it even it is not compatible with it.

![image](https://github.com/jhass/nextcloud-keeweb/assets/6613614/521331e6-990c-4dd0-bc2a-91c4d8d4417a)
