### ISSUE TITLE
[BUG] It does not work in Nextcloud 28

### ISSUE THREAD

**Issue by ssergio-ll** [jhass/nextcloud-keeweb#232]
It no longer works in Nextcloud 28.

**Comment by arnowelzel** [comment]
https://github.com/jhass/nextcloud-keeweb/pull/231 is already merged to fix this - however this does not work fully yet and since KeeWeb itself is not maintained any longer, I not sure, how long KeeWeb for Nextcloud can be offered at all.

**Comment by arnowelzel** [comment]
Closed with #231.
