### ISSUE TITLE
NC 28: File will not be opened with KeeWeb

### ISSUE THREAD

**Issue by ssergio-ll** [jhass/nextcloud-keeweb#233]
I have a file with passwords in Nextcloud. Before updating to Nextcloud 28, if I clicked on the file, KeeWeb would open and I could access it. Now, since the update to Nextcloud 28, it only allows me to open files from my PC, not files uploaded to Nextcloud.

**Comment by arnowelzel** [comment]
When using index.php in the URL it may not work, but I don't know why. Please check, that you don't have index.php in the URL:

1. Add the following setting to `config/config.php`: `'htaccess.RewriteBase' => '/'`
2. Run the following OCC command to update `.htaccess`: `php occ maintenance:update:htaccess`

So the URL of KeeWeb should be like this: `https://yourserver.example/apps/keeweb/`

**Comment by ganomi** [comment]
Having the same issue after upgrading to Nextcloud 28.

My server is running under https://yourserver.example/nextcloud/
Therefore i set 'htaccess.RewriteBase' => '/nextcloud/'

Now index.php is not part of the path anymore but it is still not working because /nextcloud/ is not part of the path. The currently constructed path is https://yourserver.example/apps/keeweb/?open=/KeyPass.kdbx

Any quick tips?

**Comment by arnowelzel** [comment]
Try it with rewrite base "/nextcloud/" including the trailing slash.

**Comment by ganomi** [comment]
I tried both variants. Unfortunately same negative result. Made sure to regenerate htaccess and also restarted php-fpm and apache each time.

**Comment by arnowelzel** [comment]
I will have a look into that later and try to reproduce this problem.

**Comment by NorbertBerlin** [comment]
nextcloud 28 generate the link : https://yourserver.example/apps/keeweb/?open=/filepath/myDb.kdbx

this link works correct: https://yourserver.example/nextcloud/index.php/apps/keeweb/?open=/filepath/myDb.kdbx

the difference is **nextcloud/index.php/**

**Comment by arnowelzel** [comment]
> nextcloud 28 generate the link : https://yourserver.example/apps/keeweb/?open=/filepath/myDb.kdbx
> 
> this link works correct: https://yourserver.example/nextcloud/index.php/apps/keeweb/?open=/filepath/myDb.kdbx
> 
> the difference is **nextcloud/index.php/** (nextcloud is the path, where nextcloud is installed)

In this case, `.htaccess` is not update properly.

**Comment by florian-forestier** [comment]
Hi @ganomi, @NorbertBerlin  & @arnowelzel, thanks for all the context & details you sent here!

I'm looking on it, I hope I will be able to send a PR today :smile:
