### ISSUE TITLE
Wrong KDBX file path in Keeweb when file is favorited

### ISSUE THREAD

**Issue by Petersoj** [jhass/nextcloud-keeweb#237]
If the Keepass/Keeweb passwords file (.kdbx file) is favorited via Nextcloud's file manager, when you navigate to `/apps/files/favorites` and click on the .kdbx file, the embedded Keeweb instance opens correctly within Nextcloud, but it uses the wrong path to the KDBX file. For example, if the favorited .kdbx file is located at `/Admin/Passwords/passwords.kdbx`, if you click on this file in the favorites tab at `/apps/files/favorites`, Keeweb attempts to open `/passwords.kdbx` instead of `/Admin/Passwords/passwords.kdbx`. Opening the file at its original location (not through the favorites tab) works fine though.

Nextcloud version: `28.0.1`
Keeweb app version: `0.6.17`

**Comment by arnowelzel** [comment]
You may give 0.6.20 a try when it's released, it contains a possible fix for that (thanks @ShGKme).

**Comment by Petersoj** [comment]
@arnowelzel yep that fixed it. Thanks!
