### ISSUE TITLE
NC29 compatibility / release?

### ISSUE THREAD

**Issue by luxzg** [jhass/nextcloud-keeweb#245]
Greetings all!

Just to start, yes - I have seen the notices.

But I am still wondering, perhaps version for NC28 works already on 29 unchanged, has anyone checked, tested?

Since @florian-forestier did the great work on NC28 perhaps NC29 release can be made, despite the upstream shortcomings?

And big thanks to everyone that worked on this app!

**Comment by arnowelzel** [comment]
I can do a test and update the compatibility information if it still works. But the situation with KeeWeb itself did not change yet. The latest official release is still 3 years old and this is the upstream for Nextcloud KeeWeb: https://github.com/keeweb/keeweb/releases

**Comment by arnowelzel** [comment]
I just pushed a new release with updated compatibility information, since it still works fine thanks to the work of @florian-forestier.

**Comment by luxzg** [comment]
Thank you both! 😊
