### ISSUE TITLE
Keeweb destroys kdbx file?!?

### ISSUE THREAD

**Issue by realwuffi** [jhass/nextcloud-keeweb#246]
I have my KeePass file in my Nextcloud instance and sync it to Android and Linux by opening it through webdav.
(Linux with mono runtime and Android using Keepass2Android app)

Since the update to Nextcloud 29 only Keeweb can read my database, on Linux and Andoid I get the following error:

![image](https://github.com/user-attachments/assets/8057683f-a2f5-4aed-887b-6e6b2d9a1c44)

Anyone else has that problem? Would really appreciate any help.
I'm a bit worried now.... argh.... also looks like there is no export function on Keeweb?

**Comment by ryester19** [comment]
Just had this happen to me as well. After a sync about 3 days ago, the database corrupted and I lost about 20 entries. Threw the same error when I tried opening with Keepass, although could still open with Keeweb and KeepassXC.

On Android, I use the Nextcloud app to sync, and KeepassDX to open/edit. I've also been editing and syncing with latest Nextcloud Keeweb

@realwuffi Were you also editing and syncing the Keepass database using Nextcloud Keeweb?

**Comment by realwuffi** [comment]
Yes, sometimes I edited the file with NextCloud Keeweb,
on Android I only used Keepass2Android app using the WebDav (open URL) to sync
And on Linux I only used the Windows KeePass application running with Mono

I was able to open the files also with NextCloud KeeWeb app, exported it as XML and imported into a new KeePass file on Linux.
Since then I have not tried again to sync it with NextCloud .

**Comment by arnowelzel** [comment]
Please try KeepassXC as well

**Comment by ryester19** [comment]
Does appear to be Keeweb causing the corruption

Change 1 letter in a random database entry using KeepassDX, sync with Nextcloud app: No problems
Revert the change in Keeweb and use its built-in webdav sync to save: Corrupted database

**Comment by arnowelzel** [comment]
You can verify this using https://app.keeweb.info - create a test database, open it in https://app.keeweb.info and see what happens when you edit it there and download it again.

**Comment by jhass** [comment]
I believe you guys are seeing https://github.com/keeweb/keeweb/issues/2001

**Comment by realwuffi** [comment]
Okay, I have changed the database version back to v3, with that it also works with KeeWeb and my Android app again.
I'm not sure if there comes a disadvantage with that, but for now it works.

Thanks for your feedback!

**Comment by arnowelzel** [comment]
I also added a note in the README file, so people are aware that KDBX 4 is not supported. Unfortunately, KeeWeb does also not warn about this, when you try to open a file in this format.
