### ISSUE TITLE
TOTP number generator not working with incorrectly padded secret

### ISSUE THREAD

**Issue by Smolli** [jhass/nextcloud-keeweb#249]
For a long time I didn't understand, why the TOTP number generator didn't work for my Twitch account. Today I found out, that my Twitch secret was generated with four additional = chars at the end (for whatever reason). So the OTP string looked like `[..]F3FLTQ%3D%3D%3D%3D&period=[..]`.

As far as I understand the implementation of Base64 padding symbols are mandatory if the used algorithm is not resilient against the missing padding, and additional `=` characters should be ignored just like blank spaces and new lines. So in theory I should be able to add as many or as little `=` chars as I like.

Turns out, after I removed the four trailing `%3D`s, the number generator worked just fine. Other applications (like KeepassXC, e.g.) worked all the time. Maybe it's a good idea to make the used algorithm less prone to break when the string is padded incorrectly.

**Comment by jhass** [comment]
Please report this to upstream, this repo merely is an integration. https://github.com/keeweb/keeweb
