### ISSUE TITLE
Where does keeweb/template/keeweb.php come from?

### ISSUE THREAD

**Issue by nickvergessen** [jhass/nextcloud-keeweb#28]
This obfuscated thing should be listed in this repo somewhere.

**Comment by jhass** [comment]
It's generated as part of the dev-setup as detailed in the readme. See also https://github.com/jhass/nextcloud-keeweb/blob/master/bin/build

**Comment by nickvergessen** [comment]
Yeah I get that, but I can't see a bower file or anything else which shows me what is being installed by the build script.
It also switches into `keeweb-source` which seems to not exist. Do I need to clone https://github.com/keeweb/keeweb into that directory?

**Comment by jhass** [comment]
Yes, as detailed in the readme.
