### ISSUE TITLE
More information in README

### ISSUE THREAD

**Issue by paulfantom** [jhass/nextcloud-keeweb#3]
`README.md` says:
> This integrates the two with each other.

It would be good to provide some screenshots so everyone could see how this integration looks like.

**Comment by jhass** [comment]
I considered it but then it's be pretty boring, it's just keeweb with the nextcloud header above it. Showing that it opens when you click on a kdbx file is rather difficult with a screenshot ;)

I'd probably accept a PR anyway if it adds something nice ;)
