### ISSUE TITLE
How to open KDBX from Files App?

### ISSUE THREAD

**Issue by Offerel** [jhass/nextcloud-keeweb#31]
After enabling the App, how can i open a KDBX File directly from the Files App? Is this not possible? In my case, if i click on a KDBX File, it starts to download, instead of opening in KeeWeb.

**Comment by Yamakasi** [comment]
This is not possible I thought but would be nice. I think you need local webdav to use, but webdav is not that stable :(

**Comment by Offerel** [comment]
In the meantime it seems to work. I had tested this with NC 10.0.1 directly after installing the App it didn't work. After this, i updated to 10.0.2 and clicked a KDBX File. It opened directly in KeeWeb. Today i updated to 11.0 and the whole App didn't. The is another issue open with this Problem.
