### ISSUE TITLE
NC 11 support

### ISSUE THREAD

**Issue by Yamakasi** [jhass/nextcloud-keeweb#32]
Is it possible to add NC11 support ?

**Comment by blubbsy** [comment]
yeah would be nice.

**Comment by HolgerHees** [comment]
I changed the max "supported" version number in "info.xml"  to 11

but now i get a "Content Security Policy" exception.

**Comment by Offerel** [comment]
same here

**Comment by Yamakasi** [comment]
I started to do that by default, so that is why I added this issue.

**Comment by Offerel** [comment]
13:16:46.867 Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src 'nonce-WTE1UUdQWVVwemM5VlpYSmRZakljc0JRTWExbkZrbkhnYlNwdTlTRThDQT06TFNrZ2NvOWpsbFpmQnQ2OUo2ZThFNllmWTk4MlZXS0swZHpkajR5eGgyST0='  'unsafe-eval'"). 1 keeweb:1


13:16:48.162 Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src 'nonce-WTE1UUdQWVVwemM5VlpYSmRZakljc0JRTWExbkZrbkhnYlNwdTlTRThDQT06TFNrZ2NvOWpsbFpmQnQ2OUo2ZThFNllmWTk4MlZXS0swZHpkajR5eGgyST0='  'unsafe-eval'"). 1 keeweb:13


13:16:48.575 Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf https://cloud.mydomain.com/apps/keeweb/manifest.appcache blockiert ("default-src 'none'"). 1 (unbekannt)

**Comment by Salzi** [comment]
I was able to run it under nextcloud 11 with just a few modifications. I am neither a php nor a nextcloud developer. So therefore I don't know if it's safe or not. The only thing I could tell is, that it works in my setup without a visible error. If you like I could create a PR.
What I did:

keeweb/appinfo/app.php
Line 76: replace 
```
if ($params['app'] == "keeweb") {
```
with
```
if ($params['app'] === "keeweb") {
```

Line 85: replace 
```
\OC_Hook::connect('OC_App', 'pre_disable', '\OCA\Keeweb\AppInfo\Hooks', 'pre_disable');
```
with
```
Util::connectHook('OC_App', 'pre_disable', '\OCA\Keeweb\AppInfo\Hooks', 'pre_disable');
```

keeweb/controller/pagecontroller.php
Line 89: replace
```
'name' => $file.' on '.OCP\Util::getServerHost(),
```
with
```
'name' => $file.' on '.\OCP\IRequest::getServerHost(),
```

maybe that helps ...

**Comment by Yamakasi** [comment]
Hi thanks, but it doesn't fix it here. I need to investigate.

What PHP version are you on ?

**Comment by Salzi** [comment]
@Yamakasi PHP Version 7.0.14-1

**Comment by Yamakasi** [comment]
# sudo -u www-data php occ app:check keeweb
App is compliant - awesome job!

**Comment by Salzi** [comment]
hmm without the modifications you should see some errors and thats why it didn't work for me. After fixing them I enabled the app and it just worked...
I'm soory but as I said I'm not a php developer and I'm probably not the right person to fix this issue ;-) but whats the error you see?

**Comment by Yamakasi** [comment]
I don't see an error, just a blank page, that is the issue :(

**Comment by Salzi** [comment]
sorry no idea. I guess you have to wait for @jhass

**Comment by Offerel** [comment]
PHP Fatal error:  Class 'OCA\Keeweb\AppInfo\Util' not found in /var/www/html/nextcloud/apps/keeweb/appinfo/app.php on line 85

**Comment by blubbsy** [comment]
`pp:check keeweb
PHP Warning:  Version warning: Imagick was compiled against Image Magick version                                                                                                                                1673 but version 1686 is loaded. Imagick will run but may behave surprisingly i                                                                                                                               n Unknown on line 0
Analysing /var/www/nextcloud/apps/keeweb/appinfo/app.php
 2 errors
    line   77: == - is discouraged
    line   85: OC_Hook - Static method of private class must not be called
Analysing /var/www/nextcloud/apps/keeweb/controller/pagecontroller.                                                                                                                               php
 1 errors
    line   89: OCP\Util::getServerHost - Method of deprecated class must not be                                                                                                                                called
App is not compliant
`

**Comment by Salzi** [comment]
@blubbsy before I started I had the same  errors as you (not the imagick error). After the changes (see above or see the PR #33) it worked for me technically. But I still have a lot of errors in the log.

**Comment by Yamakasi** [comment]
Hi thanks for the update!

I still get a blank page, what should I check for you to give some feedback ?

**Comment by mcasviper** [comment]
I have a blank page, too. PHP 5.6 if this is interesting for you. 
If you need more details please let me know.

**Comment by onny** [comment]
For me it works, Nextcloud 11, PHP7

**Comment by Yamakasi** [comment]
I have also NC 11 with PHP7, re-enbled and still blank page.

**Comment by jhass** [comment]
Try clearing your cache. Make sure you see the right version number when accessing `/index.php/apps/keeweb/manifest.appcache`.

**Comment by Offerel** [comment]
i get the following error:

Exception: template file not found: template:keeweb

    /var/www/html/nextcloud/lib/private/legacy/template.php - line 201: OC\Template\TemplateFileLocator->find('keeweb')
    /var/www/html/nextcloud/lib/private/legacy/template.php - line 84: OC_Template->findTemplate('', 'keeweb', 'keeweb')
    /var/www/html/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php - line 151: OC_Template->__construct('keeweb', 'keeweb', '')
    /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 113: OCP\AppFramework\Http\TemplateResponse->render()
    /var/www/html/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Keeweb\Controller\PageController), 'keeweb')
    /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Keeweb\\Cont...', 'keeweb', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /var/www/html/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /var/www/html/nextcloud/lib/base.php - line 1010: OC\Route\Router->match('/apps/keeweb/ke...')
    /var/www/html/nextcloud/index.php - line 40: OC handleRequest()
    {main}

**Comment by jhass** [comment]
@Offerel what exact steps did you take to install it?

**Comment by JSoko** [comment]
Keeweb 0.3.0 works here without any problem under NC 11.0.0.1...

**Comment by Offerel** [comment]
I have downloaded the master.zip from this github via wget. Extracted the keeweb directory to the apps directory of NextCloud. Thema chown -R Webserver User and activated the App Insider NextCloud. After this a Database Update Dialog appeared. Thats all...

**Comment by Offerel** [comment]
Today, i have seen, that there is new Release. Don't know why i haven't seen this yesterday. I have now downloaded again using the Release 0.3.0.tar.gz and made the same steps as above and now it seems to work. No Error Message in Nginx or NextCloud Logfiles found. Sorry for confusing you.

**Comment by jhass** [comment]
Yes, please always use releases, the repository stores the source code of the app and the helper scripts to make a build, but not the build itself.
