### ISSUE TITLE
[Feature Request] Include more ciphers ? 

### ISSUE THREAD

**Issue by mightyBroccoli** [jhass/nextcloud-keeweb#35]
Is it possible to include the TwoFishCipher or the Serpant cipher eg. from the official plugins list for keepass? 
[Serpent Cipher](https://github.com/drizzt/KeePass-SerpentCipher) @drizzt

[TwoFishCipher](http://gogogadgetscott.info/keepass/twofishcipher/)

**Comment by jhass** [comment]
Please note that this project only integrates [Keeweb](https://keeweb.info) and Nextcloud. Please direct feature requests not concerning that integration to the respective upstream projects, in this case Keeweb's [issue tracker](https://github.com/keeweb/keeweb/issues).
