### ISSUE TITLE
syncing back gives me a 401

### ISSUE THREAD

**Issue by HolgerHees** [jhass/nextcloud-keeweb#36]
Hi,

i recently updated to version 0.3.0. With that I can run keeweb with nextcloud 11. I'm able to open a file. But if I add or modify some data and try to sync it back, then the first HEAD request gives a 401 and nothing is synced back.

**Comment by Echse27** [comment]
Same here: 
After install the KeeWeb App inside NC11.0.0, you can choose a .kdbx file only one time by klicking the file itself.
When you edit a entry or add one, there is no sync back to the main .kdbx database.
Error: HTTP status 401
So now i cant found a way to drop the file from the WebApp...

**Comment by koarlmichael** [comment]
The same error here. Must disable the app because it does not work.

**Comment by tflidd** [comment]
related to: https://github.com/jhass/nextcloud-keeweb/issues/21 ?

**Comment by Juliku** [comment]
Same here, is there any recent solution to this?

**Comment by Kuppit** [comment]
Same problem here

**Comment by GitHubGeek** [comment]
Same problem here running `wonderfall/nextcloud:12.0` HTTP 401 error messages in sync result

**Comment by arnowelzel** [comment]
Same here as well :-(

**Comment by jhass** [comment]
Somebody that can reproduce needs to dive in and debug.

Perhaps it's an expired session or something...

**Comment by arnowelzel** [comment]
Probably this is already fixed with the latest version. So far it did not happen again.

**Comment by GitHubGeek** [comment]
Mine broke again - any pointer to where to start debugging?

**Comment by arnowelzel** [comment]
@GitHubGeek first check the log of Nextcloud what exactly happened. And maybe the web developer console of your browser (Firefox, Chrome) to check the HTTP requests and maybe JavaScript console/debugger may also be helpful.

**Comment by GitHubGeek** [comment]
Thanks @arnowelzel - Know anything about the GET param `requesttoken` ? My first assumption is that it's the CSRF token required by NextCloud, and it's stored somewhere (localStorage?) by KeeWeb (If not generated on the fly)

Somehow the value is corrupted or not generated correctly, causing all requests from KeeWeb to NextCloud to fail

**Comment by arnowelzel** [comment]
It seems, KeeWeb may not get the CSRF token in the first place when opening the kdbx file and therefore can not send it to Nextcloud. However I did not manage to reproduce this case here. You can add Keeweb to an opt out list in Nextcloud so CSRF tokens are not need for this client. See here:

https://docs.nextcloud.com/server/14/admin_manual/configuration_server/config_sample_php_parameters.html

I did not check yet, what UserAgent is used by Keeweb - but this setting may help.

**Comment by GitHubGeek** [comment]
Managed to reproduce the issue - using a different computer that I _don't_ use daily

1. On 25/2 I've opened a new kdbx file, no issues, sync works
1. I didn't use the PC until today (2/3); NextCloud is still logged in
1. Opened the kdbx within KeeWeb (Not through NextCloud File List) 
1. Getting 401

I didn't have time to do further debugging - Perhaps the CSRF token has somehow expired?

**Comment by arnowelzel** [comment]
It may be that the CSRF token expires in the Nextcloud server and therefore can not be used any longer after a couple of days. In this case adding the Keeweb user agent to the `'csrf.optout'` setting in Nextcloud may help.

**Comment by arnowelzel** [comment]
I can reproduce this as well when returning to Keeweb directly without opening the database within Nextcloud. I think, it's neccessar to always open the file from Nextcloud, otherwise the CSRF token expires and can not be used any longer.

Another thing I noticed: when I try to open the database in Keeweb using WebDAV and this also just results in HTTP 401 even though keepass2android can use the very same URL without any problem. Creating an app specific password also did not help.

It seems, Keeweb has some problems with Nextcloud, but I don't know yet, what is going on exactly.

**Comment by arnowelzel** [comment]
Also see here - similar problem, but no solution yet:
https://github.com/keeweb/keeweb/issues/991

**Comment by GitHubGeek** [comment]
Thanks @arnowelzel for the info, very helpful. It seems bypassing CORS is the only workaround, hmmm

I also ran into an issue after a successful sync - For some reasons the MIME type of the kdbx file is forgotten after a sync - The file's "gear" icon became the "blank doc" icon. I couldn't find an github issue about this - Could be a fault with my nextcloud instance?

**Comment by arnowelzel** [comment]
Did you add the MIME type mapping as described in the documentation? This has to be done manually, as Nextcloud does not provide an API for plugins to add missing MIME mappings (or at least I don't know of any yet). Also note that the MIME type was changed to `application/x-kdbx`. Maybe you have to change your existing mapping if you already had one for earlier versions.

**Comment by GitHubGeek** [comment]
My `mimetypemapping.json` is currently exactly the same as the one in the README; `x-application/kdbx` didn't work at all so I had to change it

**Comment by DecaTec** [comment]
Any news on this one?

Perhaps some additional information:
If I add key entries within Nextcloud/Keeweb, I always hit Ctrl+S to save immediately. No error is shown.
Opening the same kdbx with the same maschine/browser shows me the entry I just created.

But when I switch to another maschine, opening Nextcloud/Keeweb, the entry is not shown.

Back on the first machine, trying to sync manually from within Keeweb, it gives me a HTTP 401.

**Comment by HolgerHees** [comment]
maybe an another solution we could discuss.

In the file /apps/dav/lib/Connector/Sabre/Auth Line 173

`private function requiresCSRFCheck() {
      // GET requires no check at all
      if($this->request->getMethod() === 'GET') {
          return false;
		
If we add the HEAD request here too it works fine.

I mean a HEAD request is a GET request without the BODY: So make the exception only for the GET request?

**Comment by HolgerHees** [comment]
it was to early, It will just fix the HEAD request. Not the following PUT request.

**Comment by HolgerHees** [comment]
my latest pull request will update the cached file always with the current request token.

This fixes HEAD and PUT requests and allows me to sync back again. Tested with nextcloud 17 and the latest keeweb app.
