### ISSUE TITLE
Keeweb v1.3.3 doesnt open .kdbx on Nextcloud 11

### ISSUE THREAD

**Issue by bitking** [jhass/nextcloud-keeweb#39]
Hi There,

When clicking on a .kdbx file Keeweb doesnt open te file, so i get a download prompt to download the file.

After disabling and enabling the app it works again for a while and i am not sure what is triggering the problem.

Setup:
Ubuntu 16.04
PHP7
Nextcloud 11.0.1
KeeWeb v1.3.3 (52701af, 2016-12-17)
Environment: web
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36

**Comment by jhass** [comment]
Closing in favor of #34
