### ISSUE TITLE
Do not assume being installed to the root path

### ISSUE THREAD

**Issue by agentdr8** [jhass/nextcloud-keeweb#4]
I've freshly installed Nextcloud 9.0.53 and extracted the latest release into my nextcloud/apps directory. Enabled it in the admin, and Apache throws an error:

![image](https://cloud.githubusercontent.com/assets/3790868/17459883/061ea43c-5c02-11e6-9edc-b7756cca1b74.png)

Am I doing something wrong, or does something else need changing? Nextcloud log doesn't show any errors. 

EDIT: Nevermind. I figured out it was mod_rewrite not passing through on that URL

**Comment by jhass** [comment]
So you have custom rewrite rules? It seems to work without touching any of Nextcloud rules with my production install,  which uses Apache too.

**Comment by agentdr8** [comment]
Nothing custom as far as Nextcloud, but I'm using Apache as a reverse proxy, and the frame src in templates/main.php was passing /index.php/apps/keeweb/keeweb instead of /nextcloud/index.php/apps/keeweb/keeweb.

**Comment by jhass** [comment]
Ah I see, I knew bypassing the URL generator would bite me.
