### ISSUE TITLE
Creating/Saving new entry removes version history

### ISSUE THREAD

**Issue by utahbmxer** [jhass/nextcloud-keeweb#42]
Hi, cool App.  I noticed that creating a new entry in my KeePass database using this app and then saving resulted in there being no version history for my kdbx file.  Looked in the deleted files and there was my old one.  Luckily I restored it and my versions came back.  I like the possibility of editing kdbx from inside Nextcloud, but the version overwrite/clearing is a deal breaker for me.

It appears it creates a new file with the same name and a leading period (.MyDatabase.kdbx), removes the old one (MyDatabase.kdbx) and then renames the new file to the old one.  That is why there was no version history when I checked.

**Comment by jhass** [comment]
This is due https://github.com/keeweb/keeweb/issues/514 /

**Comment by antelle** [comment]
Now we have a setting for it: `webdavSaveMethod: "put"`
More details in this comment: https://github.com/keeweb/keeweb/issues/514#issuecomment-294369243
