### ISSUE TITLE
Two factor possible?

### ISSUE THREAD

**Issue by eloo** [jhass/nextcloud-keeweb#45]
Hi,

I really like your keeweb integration for NextCloud but it seems that the kdbx file can not be synchronized if TOTP is enable. Is anyone facing the same issue?
Or is this at the moment simply not possible?

Thanks for your held
Best regards,
Eloo

**Comment by agentdr8** [comment]
I have the twofactor_totp add-in enabled and can sync my kdbx just fine using Keeweb inside of NC. Are there any errors in your web server logs?

**Comment by Eloo** [comment]
okay, will check the logs files in time

**Comment by jhass** [comment]
Got around to see the logs?

To clarify, are we talking about a database containing OTP keys or being protected with an OTP key?

**Comment by danieljkemp** [comment]
I'm seeing this too:

10.0.0.214 - - [30/May/2017:22:25:28 -0400] "HEAD /remote.php/webdav/Documents/passfile.kdbx?requesttoken=XXXXXXXX HTTP/1.1" 401 - "https://YYYYYYY/index.php/apps/keeweb/keeweb" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0"

OTP is enabled, webdav seems to fail both using the webapp, and using the keepass app. It was working at some point with TOTP enabled, not sure what changed.

**Comment by trymeouteh** [comment]
KeePassXC and KeePassDX support this. Please support this in KeeWeb!

**Comment by jhass** [comment]
I'm still confused what "this" is about. I see the following possibilities what it could be:

1. Something is broken when the Nextcloud is protected by TOTP
2. Something is broken when KDBX database is protected by TOTP (is this even possible? I haven't seen it yet)
3. Something is broken when the KDBX database stores TOTP keys in some entries.
4. Showing the current TOTP code based on a stored TOTP keys is broken.

**Comment by eloo** [comment]
working with the current version
maybe some bug in older versions
