### ISSUE TITLE
NC 12 support

### ISSUE THREAD

**Issue by rseek** [jhass/nextcloud-keeweb#47]
Is it possible to add NC12 support ?

**Comment by jhass** [comment]
Sure, I myself probably won't get to it until a stable version is released though.

**Comment by JSoko** [comment]
Just
nano /var/www/nextcloud/apps/keeweb/appinfo/info.xml
and change to
        <nextcloud min-version="11" max-version="12" />
and it works (for me)

**Comment by StopTrain** [comment]
I can confirm a version bump in info.xml is all it took.  Looks like the code is working fine.

**Comment by v1r0x** [comment]
Nextcloud 12 was released today. Changing `max-version` to `12` fixed it for me as well.
