### ISSUE TITLE
Error Open files

### ISSUE THREAD

**Issue by Sid-L** [jhass/nextcloud-keeweb#48]
I get "There was an error opening file. network error" by clicking a local kdbx-file made with Windows-KeePass. Keeweb asks for password, and then I got the error.

Nextcloud 11.0.3
nextcloud-keeweb 0.3.1

**Comment by jhass** [comment]
Do you get the same with the version hosted at keeweb.info?

**Comment by finish06** [comment]
I experience the same error.  When I enter Nextcloud via the browser, and attempt to open the .kdbx file, the system reports a ```network error```
Nextcloud 12.0.0
Nextcloud-Keeweb 0.4.0

**Comment by rgeber** [comment]
Same here. Might be worth mentioning that I had to apply the workaround explained in #34 to get to this point in the first place.
When I copy the URL used by keeweb into the browser the file is downloaded. So it should be accessible.
Also, I use an nginx reverse proxy. Could that cause any trouble?

**Comment by neacsu** [comment]
I have the same problem in Nextcloud 15.0.4 and I too use a nginx reverse proxy. Funny thing is in 15.0.0 there was no problem, after applying the workaround from #34 .
NextCloud 15.0.4
Keeweb 0.5.0

**Comment by manuelteillet** [comment]
Same problem here with nextcloud 16.0.1.
I'm using nextcloud behind a nginx reverse proxy as well and it's https.
When I hover my kdbx file in keeweb, the webdav link is http. Perhaps this is the cause of the problem.

**Comment by jhass** [comment]
Can you try the workaround from https://github.com/jhass/nextcloud-keeweb/issues/95#issuecomment-464838286?

**Comment by manuelteillet** [comment]
It works !
Thanks very much !

**Comment by tilllt** [comment]
The workaround works for me, but shouldnt keeweb follow the protocol of the host application, if its http use http and if its https use https?

**Comment by lil5** [comment]
close?

**Comment by SimJoSt** [comment]
Should be closed, because not an error specifically with the app.
