### ISSUE TITLE
Unable to open .kdbx files with App

### ISSUE THREAD

**Issue by Changer90** [jhass/nextcloud-keeweb#5]
After installing the latest release Version. I am not able to open a kdbx-File with the keeweb app. Clicking on a kdbx-File only starts the Download.

**Comment by jhass** [comment]
Did you enable the app? Do you have a "Keeweb" entry in the top left header menu?

If yes to all of the above, what's your Nextcloud version? Can you share the new output in your Browser Console (Ctrl+Shift+J on Firefox,  Ctrl+Shift+I -> Console in Chrome) after a clean page load?

**Comment by Changer90** [comment]
Yes I have enabled the App using Data -> Apps -> inactive apps -> Keepassweb -> Enable  but i cannot open a kdb or kdbx directly from nextcloud. Unfortunately my Console Log is empty. If i can help you please let me know

**Comment by jhass** [comment]
Do you think you could mail me a testaccount? (me@jhass.eu)
