### ISSUE TITLE
Have to set up Webdav once in each browser

### ISSUE THREAD

**Issue by CySlider** [jhass/nextcloud-keeweb#50]
Hi, maybe I am misunderstanding something. I have the key database (.kdbx) shared in my owncloud and access it using webdav. But I have to set this up for each new browser I am accessing my owncloud account again. Doesn't feel quite cloudish ;-)

Am I missing something?

**Comment by jhass** [comment]
If you use the plugin eventually you should be able to just click the file in the file browser, however that's a bit broken right now due to no proper upstream API.  See #34. If you use the hosted version at keeweb.info, that's nothing this tackles.
