### ISSUE TITLE
 Where is the .kdbx file after creation of a keeweb database? 

### ISSUE THREAD

**Issue by jeanrjc** [jhass/nextcloud-keeweb#53]
Hi,

So I don't really know if I did understand how keeweb for nextcloud works or if its a bug, but here is my problem.

I create a new KeeWeb DB from the KeeWeb app in Nextcloud. Now I want to synchronize it with an android phone which has NC installed and KeePassDroid.

I thought that I could just tell KeePassDroid to look for the .kdbx file under the nextcloud folder so I can get my password DB. However, I can't find that file in my nextcloud file app, nor from the phone, neither from the NC server.
Note that when I log on my nextcloud server from another computer, the DB I created does not exist anymore (or is not found by keeweb either), while it still exists from the other computer.

What do I miss ?

I have NC from a Nextcloud box, with NC 11.0.3 and keeweb app 0.4.0

Thanks

**Comment by jhass** [comment]
We can't save to webdav yet, see #43.

**Comment by jeanrjc** [comment]
Well, that wasn't really my question. But thanks for your help. 

I figured out how to make it work. Although I don't see how it's related to webdav. 
On Desktop, when I click "save file" it saves it locally. On my NC server I expected that it saved the file locally (i.e. on the server), and that I can reuse that file from everywhere. This does not happen. 

The problem boils down to the fact that one cannot create a kdbx file with the NC-keeweb app, and one needs to create it beforehand with keeweb locally and save that kdbx on its nextcloud server afterwards. Now this kbdx file can be synced and opened with NC-keeweb.

Again, I may be misunderstanding something, hence my question: What do I miss ?

**Comment by jhass** [comment]
Keeweb runs entirely client side, so to create a kdbx file on Nextcloud, it needs to be created via WebDAV, which KeeWeb does not support (yet).
