### ISSUE TITLE
[Request] Service to export passwords.

### ISSUE THREAD

**Issue by brantje** [jhass/nextcloud-keeweb#54]
Hi there,
I'm the main developer of passman, and would love to work with the dev's of this project on a new feature.
Would it be possible to create a service to export a kdbx to json? 

If so, it would be possible to import kdbx files to passman, and maybe in the future read them directly without importing

**Comment by jhass** [comment]
Maybe you're looking for https://github.com/keeweb/kdbxweb? 

This just integrates https://github.com/keeweb/keeweb with Nextcloud.
