### ISSUE TITLE
Missing "New" button on Keeweb landing page

### ISSUE THREAD

**Issue by mattsarrasin** [jhass/nextcloud-keeweb#55]
The title pretty much says it. I don't see the nice "+" icon between "open" and "more". Any clues?

Operating system: Debian GNU/Linux 8.8 (jessie) 4.5.1-std-1
Web server: nginx 1.10.3-1
Database: postgresql-9.6
PHP version: 5.6.30
Nextcloud version: 12.0
Keeweb version: 0.4.0

**Comment by jhass** [comment]
Creation via webdav is not supported upstream, see #43. Please use a standalone version of keeweb for usages outside Nextcloud/webdav.
