### ISSUE TITLE
Can not find my kdbx file :-(

### ISSUE THREAD

**Issue by ZenImagine** [jhass/nextcloud-keeweb#58]
Hello,

1)
I opened the kdbx file from my local desktop with the keeweb app on nextcloud.
He told me that the kdbx file would be saved on my server.
I moved nextcloud on a new domain.
Since today my file has disappeared (it is no longer in files recently opened from keeweb).
Where is it stored?

2)
On keeweb I do not have a button to create a new file.
Why ?

**Comment by dupgit** [comment]
+1
'+' button disappeared and I can not get my already created databases. Any hints ?

**Comment by Chumachos** [comment]
+1
I don't have any file, it's necessary to upload again (and all the users logged in the same browser session can access to it).

**Comment by jhass** [comment]
If you open a local file it's only cached inside your browser, it's not actually saved onto the server.

Creating new files is disabled to avoid confusion exactly around this issue. I would also disable opening local files but didn't see an option to.
