### ISSUE TITLE
PHP Parse error:  syntax error, unexpected 'version'

### ISSUE THREAD

**Issue by axllent** [jhass/nextcloud-keeweb#6]
I'm not sure exactly why (the compressed `keeweb.php` makes it hard to debug), but I'm getting the following error on all releases:

`PHP Parse error:  syntax error, unexpected 'version' (T_STRING) in <nextcloud path>/apps/keeweb/templates/keeweb.php on line 6`

Any ideas?

**Comment by jhass** [comment]
Which PHP version?

**Comment by axllent** [comment]
Sorry, I probably should have stated that. PHP 5.6.24 (Debian 8.5)

**Comment by jhass** [comment]
I installed 5.6.24 but cannot reproduce :(

**Comment by axllent** [comment]
Thanks - that helps (that you could not reproduce)! I found the "issue" - if PHP's `short_open_tag = On` it breaks because php tries to parse the `<?xml ...` code as PHP.

Turning it off solved the problem, though that's more of a work-around I guess. Shall I close the issue?

**Comment by jhass** [comment]
That's interesting, I just had the same suspicion but turning them on still doesn't seem to reproduce for me.

Anyway, if it fixes it for you, I would recommend you to leave it off, that seems to be default and recommended setting anyway. I would suggest you explicitly turn it on for the sites/virtual hosts that need the feature, and urge the application authors still depending on them to stop doing that.

**Comment by jhass** [comment]
Actually doing a workaround seems simple enough, I just wish I could actually reproduce.

**Comment by axllent** [comment]
Point noted and I will do just that. I'm not even sure why it was on to be honest.

Thanks for the fast response. I love Keeweb, and now directly in Nextcloud too, awesome! Keep up the great work :) If you need me to test (tomorrow) a workaround then please let me know. I'll leave this open (for now) but feel free to close it if you prefer.

**Comment by xraMsamohT** [comment]
Same here with PHP 7.0.9. `short_open_tag = 0` solved the problem.
Thanks @axllent !
