### ISSUE TITLE
Design issue with Windows Edge

### ISSUE THREAD

**Issue by dagobert-duck** [jhass/nextcloud-keeweb#60]
Hy,

there is a issue with the design in Windows Edge.
When iopen Keeweb with Windows Edge i am seeing a completly different design. With Google Chrome it looks normal. 

See attached screenshots. 

Cheers
![keeweb-chrome](https://user-images.githubusercontent.com/16387562/31190855-a969d0ca-a93c-11e7-8a73-f3a9ff9983ff.png)
![keeweb-edge](https://user-images.githubusercontent.com/16387562/31190854-a968af88-a93c-11e7-887f-054850dfb1a1.png)

**Comment by jhass** [comment]
It seems like nobody cares about this (I don't tbh...) and given Edge will switch to Webkit/Blink this will probably resolve itself anyway.... so closing.
