### ISSUE TITLE
Can't open kdbx files

### ISSUE THREAD

**Issue by kevquirk** [jhass/nextcloud-keeweb#61]
I have a kdbx file stored on my Nextcloud server. However, when I click on it from the browser, it just asks if I want to download, it doesn't open in Keeweb. Also, if I then go in to the Keeweb app, and click "Open" it opens a popup asking me to load a local file, not one from within Nextcloud.

If I download my kdbx, and then open it in Keeweb, it works, but it tells me that it will be "stored in Keeweb" so it doesn't then update my kdbx file within Nextcloud.

Maybe I'm missing something here, but what's the point in having Keeweb if the functionality to integrate with Nextcloud isn't there? I really hope I'm missing something, as I'd love to start using Keeweb.

Thanks!

**Comment by kevquirk** [comment]
Fixed using details from another issue.

**Comment by pywhy** [comment]
@kevquirk can you link us how did you fix it please ? :)
