### ISSUE TITLE
Master Key Expired

### ISSUE THREAD

**Issue by kevquirk** [jhass/nextcloud-keeweb#62]
Every time I open my kdbx file, I enter my master key, but then Keeweb prompts me for a new key stating that "Master Key Expired" this happens every time I open by database.

How can I stop this from happening?

Thanks!

**Comment by jhass** [comment]
This sounds like an upstream issue, please report it at https://github.com/keeweb/keeweb

**Comment by kevquirk** [comment]
I've just been playing around and have actually "fixed" it myself. Just in case anyone else is having a problem:

1. Open your DB, then click on the "cog" (settings) icon.
2. From the left-hand pane, select the DB file you wish to "fix".
3.  Click "show advanced settings" if they are not displayed.
4. Change setting "Ask to change key after (days):" to <blank>, or whatever you wish the timeout to be on for the master key.

For some reason, mine was set to "1" so my master key would expire every day.

Hope this helps others.
