### ISSUE TITLE
.kdbx not opening in nextcloud

### ISSUE THREAD

**Issue by Ser1ous1** [jhass/nextcloud-keeweb#64]
Nextcloud 12.0.3
Firefox 57.0 (64-Bit) 

1. I've enabled the keeweb app and tried to open my existing kdbx DB, but it shows up as download.
2. I've disabled the app and re-enabled it and it still won't work.

- Open the file from my local Machine works well.

Please Fix!

**Comment by ggeorgg** [comment]
see #34

**Comment by Ser1ous1** [comment]
No update coming? NC 13 will be out soon

**Comment by Thatoo** [comment]
Would that plugin not help to solve the problem?
https://github.com/vavrecan/keeweb-local-server

**Comment by jhass** [comment]
Why do you spam this across all issues?

**Comment by Thatoo** [comment]
Sorry, it wasn't my intention to spam someone, my mistake... And sorry my discovery of this plugin can't help with this issue.

**Comment by jhass** [comment]
Try 0.5.0. Take care to follow the manual required steps as outlined in the readme when updating.
