### ISSUE TITLE
Request: Separate the database save and close functions to a seperate tab from the password settings

### ISSUE THREAD

**Issue by BAS1350** [jhass/nextcloud-keeweb#66]
![image](https://user-images.githubusercontent.com/34751369/34270490-f7fe0eec-e64d-11e7-8e06-371f51936121.png)

Because master password field is on the same page as the save button, when saving changes and closing the file, the browser may autofill the master password section and save the new entry when a user updates and closes the DB.

This is particularly troublesome when you are using a key file only, as it could potentially add a password to the database that should not exist if a user is not careful.

Apologies if there is an easy workaround for this that I am unaware of.

**Comment by jhass** [comment]
Please report upstream at keeweb/keeweb.
