### ISSUE TITLE
KdbxError: Error FileCorrupt: no meta node 

### ISSUE THREAD

**Issue by alexknobbe** [jhass/nextcloud-keeweb#68]
Goodafternoon.

Some time ago i have imported an kbx file in to keeweb.
This morning i get the following message: KdbxError: Error FileCorrupt: no meta node 

How can i resolve this as my kbx file is not located in my files but is loaded in the app?

Thank you

**Comment by jhass** [comment]
Please report upstream at https://github.com/keeweb/keeweb
