### ISSUE TITLE
Network error loading plugins

### ISSUE THREAD

**Issue by SHKEd** [jhass/nextcloud-keeweb#72]
RU: Не могу загрузить перевод, потому что плагины не доступны, выводит ошибку. Как загрузить перевод то?

TRANSLITE GOOGLE:
I do not have plugins and I can not load language.How????

Network error loading plugins =((((

keeweb:21 Refused to connect to 'https://plugins.keeweb.info/plugins.json?_=1516644196399' because it violates the following Content Security Policy directive: "connect-src 'self' ".

KeeWeb v1.5.0 (4c4a308, 2017-05-22)
Environment: web
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.97 Safari/537.36 Vivaldi/1.94.1008.44

**Comment by chartmix** [comment]
Probably I got the same problem.
I would like to install the keewebhttp Plugin but got the error: "error loading plugins".
The log says:
[INFO ] 2018-02-03T16:54:02.195Z [app] Started in 8248ms ¯\_(ツ)_/¯
[DEBUG] 2018-02-03T16:54:09.363Z [plugin-gallery] Loading plugins...
[ERROR] 2018-02-03T16:54:09.438Z [plugin-gallery] Network error loading plugins

I am using Nextcloud 12.0.5 and Keeweb 1.5.0 on a shared webspace.

**Comment by Nasty** [comment]
Hi, 
i can load the plugin gallery.

Add this 5 lines to this file keeweb/appinfo/app.php at line 22 (after parent::__construct...)

        $manager = \OC::$server->getContentSecurityPolicyManager();
        $policy = new \OC\Security\CSP\ContentSecurityPolicy();
        $policy->addAllowedConnectDomain('https://plugins.keeweb.info');
        $policy->addAllowedScriptDomain('https://plugins.keeweb.info');
        $manager->addDefaultPolicy($policy);

**Comment by arnowelzel** [comment]
Installing new plugins makes no sense as the app runs just as a client side JavaScript and there is no place to store the plugins anyway.

So it would be better to remove the plugins section completely for the Nextcloud version.

**Comment by jhass** [comment]
I guess some plugins and language packs can make sense even when run here, would be nice if somebody can play around with this and report experiences and if everything is cool send a PR for the necessary CSP adjustments :)

If it really doesn't work we should ask upstream for a config option to hide the plugin functionality as a whole.

**Comment by dragonandy** [comment]
I manage to install the plugins and they work correctly. Add these two lines to the keeweb/controller/pagecontroller.php under the getCSP() function

```php
		$csp->addAllowedScriptDomain('https://plugins.keeweb.info');
		$csp->addAllowedConnectDomain('https://plugins.keeweb.info');
```

all plugins work

```log
[INFO ] 2019-03-02T07:56:43.553Z [plugin] Installing plugin from url https://plugins.keeweb.info/translations/ru-RU/
[DEBUG] 2019-03-02T07:56:43.553Z [plugin] GET https://plugins.keeweb.info/translations/ru-RU/manifest.json?ts=1551513403553
[DEBUG] 2019-03-02T07:56:44.849Z [plugin] GET OK https://plugins.keeweb.info/translations/ru-RU/manifest.json?ts=1551513403553 1295ms
[DEBUG] 2019-03-02T07:56:44.849Z [plugin] Loaded manifest {"version":"1.13.0","manifestVersion":"0.1.0","name":"language-russian","description":"Russian language","author":{"name":"KeeWeb","email":"antelle.net@gmail.com","url":"https://keeweb.info"},"licence":"MIT","url":"https://plugins.keeweb.info/translations?lang=ru-RU","resources":{"loc":"rEDFEfzgh79U8ODDVO6YFYk+1kucs4KwOvb9vdC8/56WJ3dz+eJgy3kwbF9YF2dMv+pl6mqnvoTBIqv5SUkMRPRBHuqqaonlnFu+rfAloPBaAf43x27LvbikwjQ5nRQyaAFMx73DRWSWJ395MsqTkgusPjIyfLN0zXrW6mVSZYSONJSow1aQABhfx8hYBGFqnt6Z8vtqh3s2dGG07ENlTaJswLyHV+TEpV6/visw/kQ8FALH8xgFA7n4FcbZ0W6DecNjZ3+y1CGv57Te9FgnORIJZT52P8nE52SFu7Aokya7Djm+k5hWWeAgLWWcxT40FtDbRBiGGv5nbmPCtklP5g=="},"locale":{"name":"ru-RU","title":"Русский","flag":"🇷🇺"},"publicKey":"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0oZB2Kt7AzRFNqf8FuO3C3kepHPAIQYiDPYdQxHcsiaFCwyKVx6K1cE/3vBhb8/2rj+QIIWNfAAuu1Y+2VK90ZBeq6HciukWzQRO/HWhfdy0c7JwDAslmyGI5olj0ZQkNLhkde1MiMxjDPpRhZtdJaryVO5cFJaJESpv3dV6m0qXsaQCluWYOSNfSjP9C8o2zRVjSi3ZQZnZIV5pnk9K2MtlZIPXrN9iJiM5zZ9DTSnqApI6dC9mX4R3LvGN+GTovm9C8Crl+qb106nGRR3LcweicDnPyMtZLa/E0DBpWYxUVLDp6WeLhxoUBr+6+t3Xp9IDnPoANDQXJXD0f1vQxQIDAQAB"}
[INFO ] 2019-03-02T07:56:44.850Z [plugin:language-russian] Loading plugin with resources loc (url)
[DEBUG] 2019-03-02T07:56:44.850Z [plugin] GET https://plugins.keeweb.info/translations/ru-RU/ru-RU.json?ts=1551513404850
[DEBUG] 2019-03-02T07:56:45.225Z [plugin] GET OK https://plugins.keeweb.info/translations/ru-RU/ru-RU.json?ts=1551513404850 375ms
[DEBUG] 2019-03-02T07:56:45.225Z [plugin:language-russian] Resource data loaded loc 375ms
[DEBUG] 2019-03-02T07:56:45.228Z [plugin:language-russian] Resource signature validated loc 2ms
[INFO ] 2019-03-02T07:56:45.228Z [plugin:language-russian] Installing plugin resources
[DEBUG] 2019-03-02T07:56:45.230Z [plugin:language-russian] Plugin locale installed
[DEBUG] 2019-03-02T07:56:45.230Z [storage-plugin-files] Save language-russian_ru-RU.json
[DEBUG] 2019-03-02T07:56:45.232Z [storage-plugin-files] Saved language-russian_ru-RU.json 3ms
[INFO ] 2019-03-02T07:56:45.233Z [plugin:language-russian] Install complete 383ms
```

**Comment by dragonandy** [comment]
#97
