### ISSUE TITLE
App can not be activated

### ISSUE THREAD

**Issue by jamfx** [jhass/nextcloud-keeweb#74]
Hi,
I downloaded and unpacked the App in my AppFolder. But after unpacking in App-Folder, I can not activate the App. Only "Remove" is available in the Administration. "Activate" is greyed out. The app is only shown in "deactivated Apps".
Surely I did something wrong. But I need a hint to get it solved. So please advise me.

Server:
Latest NextCloud Version: 13.0.1
PHP 7.1

Do you need more Info?
Thanks for your help in advance
JamFX

**Comment by jhass** [comment]
See #67
