### ISSUE TITLE
can't open or work with keepass file

### ISSUE THREAD

**Issue by fazlerabbi37** [jhass/nextcloud-keeweb#75]
Hello there,
I have hosted a Nextcloud 12 instance in a Ubuntu 16.04 and install keeweb from the apps menu. I have uploaded a test.kdbx using Chromium into the root folder of my Nextcloud. However I haven't been able to use keeweb due to a few problems:
1. When I double click the test.kdbx file it downloads instead of opening in keewee.

2. After going to keeweb app when I click Open it opens the file browser in my pc. If I select a keepass database of .kdbx format it asks me for database password. Upon entering the password a loading circle keeps circling. On console I got a  error saying:
`KdbxError
code
:
"NotImplemented"
message
:
"Error NotImplemented: Random not implemented"
name
:
"KdbxError"
__proto__
:
Object`

3. On the WebDEV option I gave http:ip/nextcloud/remote.php/webdav/test.kdbx in Url, my user name in User field and my password in the Password field. Upon clicking ok I get e Error: HTTP status 401.

I already read issue #34 and tried and failed to apply solutions given in comment [1](https://github.com/jhass/nextcloud-keeweb/issues/34#issuecomment-269106088) and [2](https://github.com/jhass/nextcloud-keeweb/issues/34#issuecomment-303328968). 
It would be very kind if anybody can help me out with this. Thanks in advance!

**Comment by stephanfriedrich** [comment]
Hi get the same issue within my browser-console-log

I create a keepassX file via https://app.keeweb.info/ downloaded it locally und uploaded it to my nextcloud 12.
after opening it in nextcloud  filesystem, it linked it correctly to keeweb-nextcloud-app.
*i got these error* after enter my keypassx-password. 

I cant figure out what todo to fix the issue #34 helped me by adding the correct mimetype

```
keeweb?config=config?file=/test.kdbx:2 Uncaught KdbxError {name: "KdbxError", code: "NotImplemented", message: "Error NotImplemented: Random not implemented"}code: "NotImplemented"message: "Error NotImplemented: Random not implemented"name: "KdbxError"__proto__: Object
random @ keeweb?config=config?file=/test.kdbx:2
getBytes @ keeweb?config=config?file=/test.kdbx:2
get @ keeweb?config=config?file=/test.kdbx:17
openDb @ keeweb?config=config?file=/test.kdbx:24
inputKeydown @ keeweb?config=config?file=/test.kdbx:24
dispatch @ keeweb?config=config?file=/test.kdbx:11
q.handle @ keeweb?config=config?file=/test.kdbx:11
```

**Comment by jhass** [comment]
What browser are you folks using?

**Comment by fazlerabbi37** [comment]
@jhass tested both on Goolge Chrome and Chromium.

**Comment by jhass** [comment]
And how did you create your databases? Does the problem show with a new database? Do you have a test database that reproduces the problem to share?

**Comment by fazlerabbi37** [comment]
I stopped using it because of this error. as far as I remember, I created the db on keepass software installed on my machine and then uploaded it to keeweb. 

---

re-production of the bug is not possible as I have upgraded to NC15 and after installing Keeweb I am getting this following error on Chromium.
```
Error loading app

Your browser doesn't support some important features we're using.

KdbxError: Error NotImplemented: AES-CBC not implemented

**Comment by jhass** [comment]
See https://github.com/keeweb/keeweb/issues/1100#issuecomment-459996957

**Comment by fazlerabbi37** [comment]
@jhass does this work now with Nextcloud 15+ and over https?

**Comment by jhass** [comment]
Tbh. I never tested this on Chrome but judging by the amount of people complaining about this, I guess it does work ;)

**Comment by CptDayDreamer** [comment]
I still got the bug using NextCloudPi with NextCloud 16.0.3 after a fresh install. A fresh install before with the same version worked fine but now it does not work in any way.

**Comment by SimJoSt** [comment]
@CptDayDreamer @fazlerabbi37 does the problem persist with the newest, just released version? https://github.com/jhass/nextcloud-keeweb/releases  
It updated the used Keeweb version.

**Comment by CptDayDreamer** [comment]
@SimJoSt fixed it already with the old version. With any NextCloud Update I had to create the mimetype file again. But with the updates of KeeWeb that's not necessary anymore, right?
