### ISSUE TITLE
Content Security Policy « frame-src »

### ISSUE THREAD

**Issue by Rambobafet** [jhass/nextcloud-keeweb#76]
Hi :)

I have no way to export my (edited) file back on my computer. Browser's console is telling me that due to Content Security Policy, the page prevented the loading of a ressource "blob:[my server's url]:uniqid" "frame-src"

```Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à blob:https://subdomain.ndd.tld/2e620ab0-19d6-44fe-8def-73b5c98802f5 (« frame-src »).```

This is displayed both when trying to save file, or doing an XML export.

Any idea why?

Thx :)

Browser : Firefox 60

**Comment by tiaga** [comment]
Hi,

The cause in the Content-Security-Policy header. As a workaround for Apache, I just modified the header on the KeeWeb page:
```
<If "%{THE_REQUEST} =~ m#\/nextcloud\/apps\/keeweb\/#">
	Header edit Content-Security-Policy "frame-src 'self';" "frame-src 'self' blob:;"
</If>
```

**Comment by jhass** [comment]
CSP is set here https://github.com/jhass/nextcloud-keeweb/blob/master/keeweb/controller/pagecontroller.php#L44-L46

PRs welcome.

**Comment by jhass** [comment]
Hi, do you still have this issue with version 0.5.0? Take care of the required manual steps outlined in the readme when updating.

**Comment by mwlczk** [comment]
@jhass I have something similar:
Content Security Policy: The page’s settings blocked the loading of a resource at http://cloud.somedoma.in/remote.php/webdav/Documents/keepass.kdbx?requesttoken=xyz (“connect-src”).

My Installation runs inside of https://github.com/hoellen/dockerfiles/tree/master/nextcloud though, so not sure if the bug is on the side of the nginx from the other project or in keeweb

**Comment by jhass** [comment]
Pay attention to the URL in your browser, including the protocol. Does it match that of the request? If not you have some kind of setup issue, that is Nextcloud thinking/seeing it's running on a different URL that what you use to access it.

**Comment by mwlczk** [comment]
@jhass you are right. the ressource blocked is http and should be http**s**.
Does anyone know how to solve this?

**Comment by jhass** [comment]
IME Usually this is in a reverse proxy scenario and about setting a HTTP header like `X-Forwarded-Proto` or the like

**Comment by mwlczk** [comment]
the workaround from #93 resolved my http vs https issue

**Comment by tiaga** [comment]
> CSP is set here https://github.com/jhass/nextcloud-keeweb/blob/master/keeweb/controller/pagecontroller.php#L44-L46
> 
> PR welcome.

Better late then never, PR is here #111
