### ISSUE TITLE
Opening databases does not work on the Favorites page

### ISSUE THREAD

**Issue by b12f** [jhass/nextcloud-keeweb#78]
Went through all the steps in #34 and was troubleshooting for ages, but the problem appears to be that I was trying to open from the favorites page

**Comment by jhass** [comment]
Can you try with 0.5.0? Seems to work for me :)

Take care of the manual required steps outlined in the readme when updating.

**Comment by maurerle** [comment]
I can't reproduce this issue. Works fine. NC 17.0.1 and 0.5.1
I think you can close this issue.

**Comment by b12f** [comment]
Yep just tried, seems to work
