### ISSUE TITLE
choosing *.kdbxfile

### ISSUE THREAD

**Issue by JSoko** [jhass/nextcloud-keeweb#8]
To improve the documentation, it should be mentioned that for using nextcloud-keeweb you just have to click on an existing *.kdbx file in your nextcloud.

Btw. Thanks, it's an great app!

**Comment by jhass** [comment]
There's no in application documentation so I'm not sure what exact wording you expect where exactly. Pull request welcome!

**Comment by JSoko** [comment]
In apps.nextcloud.com you could replace

> Open Keepass stores inside Nextcloud with Keeweb.
with

> Open Keepass stores inside Nextcloud with Keeweb just by clicking on an *.kdbx file.

https://github.com/jhass/nextcloud-keeweb/blob/master/README.md

could be changed to
This integrates the two with each other. Just click on a *.kdbx file in Your Nextcloud to open it.
