### ISSUE TITLE
Exception: template file not found: template:keeweb

### ISSUE THREAD

**Issue by david-zaletanski** [jhass/nextcloud-keeweb#80]
This is on NextCloud 13.0.4

I change appinfo maxVerison to 14 to be able to enable it. When I click the Keeweb app icon it sends me to Internal Server Error page. In logs all I found was:

![image](https://user-images.githubusercontent.com/5800264/41791380-2fd6c374-761b-11e8-8991-4465bb1707c3.png)

**Comment by jhass** [comment]
Did you install by just `git clone`ing the repo?

**Comment by david-zaletanski** [comment]
@jhass Sorry for delayed reply, appreciate the response - Yes, first I tried just extracting the latest release tar. To be sure, I just `git clone`d as well, symlinking keeweb to nextcloud/apps + setting permissions as well, same result. Any other "tweaks" needed to get it to work in latest version of nextcloud? I may have missed a step.

**Comment by jhass** [comment]
Do not use a git clone, do not use one of the GitHub generated tarballs, use the actual release tarball on the releases page.
