### ISSUE TITLE
Change media type to application/x-keepass

### ISSUE THREAD

**Issue by arnowelzel** [jhass/nextcloud-keeweb#82]
As mentioned in https://github.com/jhass/nextcloud-keeweb/pull/81#issuecomment-411772502:

At the moment KeeWeb uses the media type `x-application/kdbx`. This should be changed to `application/x-keepass` because the subtype should describe the media type, refers to KeePass, and leaves the use of further file extensions open.

**Comment by DJCrashdummy** [comment]
i'm confused... :confused: now there are 3 different versions:
- `x-application/kdbx` (old one)
- `application/x-keepass` (suggested one)
- `application/x-kdbx` (now in the readme)
