### ISSUE TITLE
Support NC14

### ISSUE THREAD

**Issue by Heidistein** [jhass/nextcloud-keeweb#83]
Since a few days (week?) nextcloud 14 is in RC state.
any plans on this support?

**Comment by twixi** [comment]
ok! wait...

**Comment by cestmoimeme** [comment]
I'm waiting too ! thanks a lot :)

**Comment by jpereztenerife** [comment]
Can we still open keeweb by clicking a kdbx file like in NC13? That would be enough for me...

**Comment by k1rb** [comment]
Keeweb was working fine for me in NC13. I had to tell the server to associate kdbx file extentions with the keeweb app and set the app's info.xml to version 13 but it worked fine. I just upgraded from 13 to 14, changed the version again and re-enabled the app. It's stable and everything still works but the body of the page is all pushed off to the left, as if the entire app is being loaded in a nav bar.

Any ideas on how I can circumvent this issue? Also, what is keeping keeweb from being updated from 12 to 13 and or 14? Someone's time or something else?

Thanks!

**Comment by zoh48gz04** [comment]
> I had to tell the server to associate kdbx file extentions with the keeweb app

Can you share with us how you did that?

**Comment by unomar** [comment]
> > I had to tell the server to associate kdbx file extentions with the keeweb app
> 
> Can you share with us how you did that?
Follow the instructions in this PR
https://github.com/jhass/nextcloud-keeweb/pull/81/files

Worked for me in NC14.

**Comment by edzoe** [comment]
Thank you. I have no issues with NC14 and keeweb :-) If you add a new kbdx file, need to do the scan again :-)

**Comment by arnowelzel** [comment]
Here neither. It would really be nice to implement the proposed changes - there are other apps there as well which require manual MIME type additions and I don't think that an API change in Nextcloud to avoid this manual step will come soon.

**Comment by onny** [comment]
Keeweb still works with Nextcloud 15 after adjusting `appinfo/info.xml

**Comment by e-alfred** [comment]
i gave @jhass a heads up on how another app solves the problem of registering mimetypes (Epub/Cbz/PDF reader app) over here but sadly it seems @jhass is not interested in it as I got no answer: https://github.com/jhass/nextcloud-keeweb/issues/67#issuecomment-449632618

**Comment by ravermeister** [comment]
Can someone create a zip for nc 15? Or is there a recent fork...?

**Comment by aalaesar** [comment]
> Also see Keepass2Android - this supports Nextcloud as storage with an offline cache on the device.

Recently, there is a lot of good apps for keepass databases.
Keepass DX is also well integrated with Android and come with a special keyboard to avoid copy/pasting logins ( because the copy memory is shared between all apps).

**Comment by arnowelzel** [comment]
It seems we are finally getting somewhere. See the comments at #81. Thank you :-).

**Comment by ravermeister** [comment]
@arnowelzel do you have a succesful build to share with us?
I can't get the build script running on my machine with current nodejs...

**Comment by ravermeister** [comment]
Thanks for the hint, with this version:
`echo390:~/repos/git/nextcloud-keeweb$ node -v
v8.15.0
`

the build seems to work (assuming this is the outpout of a succesfull build):
`> keeweb@1.7.4 postinstall /home/ravermeister/repos/git/nextcloud-keeweb/keeweb-source
> cd desktop && npm install

audited 1 package in 0.627s
found 0 vulnerabilities

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 12497 packages in 15.803s
found 0 vulnerabilities

bower                           ENOENT No bower.json present`

...the App installs and is shown, but when I want to access it I get an "Internal Server Error" on the menu Frame and the content is a blank page...

**Comment by arnowelzel** [comment]
To create a version which can just be copied to an existing Nextcloud instance, you only need to run `make dist` inside the `keeweb` folder. This creates `keeweb/build/artifacts/appstore/keeweb.tar.gz` with the content of the `keeweb` app folder in Nextcloud.

However - I was not lucky as well so far - same problem here even after applying https://github.com/jhass/nextcloud-keeweb/commit/b6584d0f55ea418da8c655543c59ddb99c730114 - sorry :-(

**Comment by arnowelzel** [comment]
Ok, it there is a file missing after the build. See https://github.com/jhass/nextcloud-keeweb/issues/16 - I have to sort out, how the build is done properly.

**Comment by arnowelzel** [comment]
Well - I did not figure out, how to get the build properly done. The missing file is copied from `dist/index.html` - but I don't find any `dist` folder anywhere after running the build.

So - I used `templates/keeweb.php` from my working version in NC14 and added the custom CSP code from [here](https://github.com/jhass/nextcloud-keeweb/blob/master/keeweb/controller/pagecontroller.php#L44-L46). With these modifications it works now in NC15 as well. Of course you still have to do the manually add the required MIME type in Nextcloud, to be able to open *.kdbx files from the file view. But so far it looks good.

You can download a working archive here: https://nextcloud.0x0c.de/s/tcEzYLB5gb8AJEY

Extract the archive to the `apps`  folder of Nextcloud and enable it in the settings, if needed. The version is 0.4.1, so this will be considered an upgrade in your Nextcloud instance, if the app was already enabled before copying the new version.

**Comment by ravermeister** [comment]
the dist folder is in keeweb-source and there is a index.html too, 
I merged the nc15-wip branch and made a new build but still no luck, so thanks for your work.

**Comment by arnowelzel** [comment]
Whatever I try - I don't get the `dist` folder at all and the missing keeweb-part is the reason for the internal server error.

**Comment by arnowelzel** [comment]
Indeed - Keeweb 1.7.4 seems not to work at all. There is also a minor glitch with the CSP, but this only causes a warning in the console, I fixed this with https://github.com/arnowelzel/nextcloud-keeweb/commit/02d0519b5c73d934712faecb2b41893020c0ba25. But this does not change anything, Keeweb 1.7.4 still does not start and there is no error at all in the console to indicate what's going on.

**Comment by arnowelzel** [comment]
JFTR: I also updated https://nextcloud.0x0c.de/s/tcEzYLB5gb8AJEY with the fixed CSP.

**Comment by arnowelzel** [comment]
I think, this is related to the change introduced here: https://github.com/nextcloud/server/commit/5b61ef9213df0ff67ebd5b9c88a8e1562f367351#diff-ea7fde28f6b4be25c841ed420fef5cdf

Also see https://github.com/jhass/nextcloud-keeweb/pull/81#issuecomment-455868846 which mentions this.

**Comment by ravermeister** [comment]
Yes I merged https://github.com/jhass/nextcloud-keeweb/blob/b6584d0f55ea418da8c655543c59ddb99c730114/keeweb/controller/pagecontroller.php

Into my fork but no luck, I get some errors during build which are ignored due to - - force flag. I'll keep trying to build 🙂 anyway your zip works 👍

**Comment by jhass** [comment]
Try 0.5.0.

Never tested it for NC14 but it should still work. Or just jump to NC15 :)

**Comment by oxivanisher** [comment]
It works great on my installation. Loving it! Thanks for all the work! :D ❤️
