### ISSUE TITLE
MIME Type Mapping Typo in README

### ISSUE THREAD

**Issue by k1rb** [jhass/nextcloud-keeweb#91]
Hello, noticed the latest readme contains a typo pertaining to `mimetypemapping.json`... Might end up causing a lot of unnecessary open issues.

Currently reads:

```json
{
  "kdbx": ["application/x-kdbx"]
}
```

Should be:

```json
{
    "kdbx": ["x-application/kdbx"]
}
```

Thanks!

**Comment by jhass** [comment]
No, the mimetype was updated according to #82. I stayed with `kdbx` since for now Keeweb handles no other type of keepass database.
