### ISSUE TITLE
Keeweb 401

### ISSUE THREAD

**Issue by Talanor** [jhass/nextcloud-keeweb#93]
Hello,

When I go to ```https://MYHOSTNAME/apps/keeweb/``` and try to open a keeweb file _via_ webDAV, I get a ```401```. So I did a little digging and found that the request sent is a ```HEAD``` request looking like this:

```
HEAD /remote.php/webdav/my/path/database.kdbx HTTP/1.1
Host: MYHOSTNAME
User-Agent: XXX
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: https://MYHOSTNAME/apps/keeweb/keeweb
Authorization: Basic XXXXXXXXXX
Cache-Control: no-cache
Cookie: nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; nc_username=USERNAME; nc_token=TOKEN; nc_session_id=SESSID; oc_music_volume=50; oc_sessionPassphrase=PASSPHRASE; ocv9965cyhq1=32B_STR
Connection: close
```

And when I replay the request it indeeds sends me a ```401```. However, if I intercept it (with burp for example) and remove the the ```Cookie``` header, it replies a ```200``` and work fine.

This issue is preventing me from using keeweb and I can't seem to find why it does that and why I seem to be the only one affected by this.

Thank you for your time. Regards,

**Comment by jhass** [comment]
Does it work for you if you open the file by clicking on it in the files app?

**Comment by Talanor** [comment]
> Does it work for you if you open the file by clicking on it in the files app?

No, it downloads the file (so no 401 either), but I believe this issue comes from bad mime-type tagging and haven't had the time to work on that (since it is not a priority either).
Note that one I have opened it that way (intercepting & removing the cookie) it works since the HEAD request doesn't have to be done again.

**Comment by jhass** [comment]
Please fix the mimetype issue and see if it works this way. Fixing NCs WebDav blacklist or Keeweb's or NCs WebDav implementation is beyond the scope of this plugin (and impossible to do from there anyway).

**Comment by Talanor** [comment]
> Please fix the mimetype issue and see if it works this way. Fixing NCs WebDav blacklist or Keeweb's or NCs WebDav implementation is beyond the scope of this plugin (and impossible to do from there anyway).

Doesn't work (the mimetype issue is fixed and keeweb prompts me for my password but some JS seem to fail):

![Web dev console screenshot](https://i.imgur.com/BhFSwMS.jpg)

Below is the text (but very badly formatted) version:

```
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
JQMIGRATE: Migrate is installed, version 1.4.0
core.js:7:542
TypeError: fileInfo.path.match(...) is null[Learn More]
script.js:28:16
fileInfos<
https://MYHOSTNAME/custom_apps/keeweb/js/script.js:28:16
filter self-hosted:311:17 <anonymous>
https://MYHOSTNAME/custom_apps/keeweb/js/script.js:24:17
<anonymous>
https://MYHOSTNAME/custom_apps/keeweb/js/script.js:11:2
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
2019-02-13T10:36:40.225Z [app] Loading config from config?file=/my/path/database.kdbx
keeweb:12:680
2019-02-13T10:36:40.791Z [app] Loaded app config from config?file=/my/path/database.kdbx 565ms
keeweb:12:840
2019-02-13T10:36:40.897Z [app] Started in 4331ms ¯\_(ツ)_/¯
keeweb:12:840
2019-02-13T10:36:50.349Z [open:/my/path/database.kdbx on MYHOSTNAME] File open request
keeweb:12:840
2019-02-13T10:36:50.350Z [open:/my/path/database.kdbx on MYHOSTNAME] Open file from storage webdav
keeweb:12:840
2019-02-13T10:36:50.350Z [open:/my/path/database.kdbx on MYHOSTNAME] Load from storage
keeweb:12:840
2019-02-13T10:36:50.351Z [storage-webdav] Load http://MYHOSTNAME/remote.php/webdav/my/path/database.kdbx?requesttoken=TOKEN
keeweb:12:680
2019-02-13T10:36:50.355Z [storage-webdav] Load error http://MYHOSTNAME/remote.php/webdav/my/path/database.kdbx?requesttoken=TOKEN 2ms
keeweb:12:680
2019-02-13T10:36:50.355Z [open:/my/path/database.kdbx on MYHOSTNAME] Storage load error network error
keeweb:12:840
2019-02-13T10:36:50.356Z [open-view] Error opening file network error
keeweb:12:1165
s.prototype.error
https://MYHOSTNAME/apps/keeweb/keeweb:12:1165
openDbComplete
https://MYHOSTNAME/apps/keeweb/keeweb:12:406087
n/<
https://MYHOSTNAME/apps/keeweb/keeweb:12:164147
load/<
https://MYHOSTNAME/apps/keeweb/keeweb:12:197305
_request/<
https://MYHOSTNAME/apps/keeweb/keeweb:12:200312
Content Security Policy: The page’s settings blocked the loading of a resource at http://MYHOSTNAME/remote.php/webdav/my/path/database.kdbx?requesttoken=TOKEN (“connect-src”). 
```

Regards

**Comment by jhass** [comment]
> `https://MYHOSTNAME/custom_apps/keeweb/js/script.js:28:16`
> `http://MYHOSTNAME/remote.php/webdav/my/path/database.kdbx?requesttoken=TOKEN`

Notice how it says `https` and `http`. See https://github.com/jhass/nextcloud-keeweb/issues/76#issuecomment-462973261

**Comment by Talanor** [comment]
> > `https://MYHOSTNAME/custom_apps/keeweb/js/script.js:28:16`
> > `http://MYHOSTNAME/remote.php/webdav/my/path/database.kdbx?requesttoken=TOKEN`
> 
> Notice how it says `https` and `http`. See [#76 (comment)](https://github.com/jhass/nextcloud-keeweb/issues/76#issuecomment-462973261)

I'll investigate but ```http://MYHOSTNAME/remote.php/webdav/my/path/database.kdbx?requesttoken=TOKEN``` Responds properly and maked me dowload database.kdbx

**Comment by jhass** [comment]
Yes, the CSP blocks the request because the protocol doesn't match the site doing the request.

**Comment by Talanor** [comment]
> Yes, the CSP blocks the request because the protocol doesn't match the site doing the request.

Yep, I couldn't change the way my reverse proxy works however, i was able to use ```overwriteprotocol```:

https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html?highlight=overwriteprotocol#overwrite-parameters

And it works fine now. Thank you for your support. =)
