### ISSUE TITLE
Error opening file: network error

### ISSUE THREAD

**Issue by e-fik123** [jhass/nextcloud-keeweb#95]
Nextcloud: 15.0.4
Keeweb: 0.5.0

Load keepass database is ok. Entering password (anypassword) produces error:
There was an error opening file
network error
<img width="652" alt="snimek obrazovky 2019-02-18 v 18 23 28" src="https://user-images.githubusercontent.com/25080278/52967527-a65bc600-33aa-11e9-9645-a655b5ace939.png">

Expected behaviour:
When entering correct password open database, when wrong password display msg.

Logs:

[DEBUG] 2019-02-18T17:22:58.608Z [app] Loading config from config?file=/Keepass/Newdatabase.kdbx
[INFO ] 2019-02-18T17:22:58.724Z [app] Loaded app config from config?file=/Keepass/Newdatabase.kdbx 115ms
[INFO ] 2019-02-18T17:22:58.792Z [app] Started in 1272ms ¯\_(ツ)_/¯
[INFO ] 2019-02-18T17:23:01.003Z [open:/Keepass/Newdatabase.kdbx on cloud.test.com] File open request
[INFO ] 2019-02-18T17:23:01.003Z [open:/Keepass/Newdatabase.kdbx on cloud.test.com] Open file from storage webdav
[INFO ] 2019-02-18T17:23:01.003Z [open:/Keepass/Newdatabase.kdbx on cloud.test.com] Load from storage
[DEBUG] 2019-02-18T17:23:01.003Z [storage-webdav] Load http://cloud.test.com/remote.php/webdav/Keepass/Newdatabase.kdbx?requesttoken=BMGA%2F%2Fqh4RogORmcTsGo3J0Garcl%2FBHgH2845arp%2FqQ%3D%3ASYmrx4zgi013elD4Kur7rNtPA95vsHDLSiR%2FpOODttw%3D
[DEBUG] 2019-02-18T17:23:01.007Z [storage-webdav] Load error http://cloud.test.com/remote.php/webdav/Keepass/Newdatabase.kdbx?requesttoken=BMGA%2F%2Fqh4RogORmcTsGo3J0Garcl%2FBHgH2845arp%2FqQ%3D%3ASYmrx4zgi013elD4Kur7rNtPA95vsHDLSiR%2FpOODttw%3D 3ms

[INFO ] 2019-02-18T17:23:01.007Z [open:/Keepass/Newdatabase.kdbx on cloud.test.com] Storage load error network error

[ERROR] 2019-02-18T17:23:01.007Z [open-view] Error opening file network error

[INFO ] 2019-02-18T17:23:05.902Z [open:/Keepass/Newdatabase.kdbx on cloud.test.com] File open request
[INFO ] 2019-02-18T17:23:05.903Z [open:/Keepass/Newdatabase.kdbx on cloud.test.com] Open file from storage webdav
[INFO ] 2019-02-18T17:23:05.903Z [open:/Keepass/Newdatabase.kdbx on cloud.test.com] Load from storage
[DEBUG] 2019-02-18T17:23:05.903Z [storage-webdav] Load http://cloud.test.com/remote.php/webdav/Keepass/Newdatabase.kdbx?requesttoken=BMGA%2F%2Fqh4RogORmcTsGo3J0Garcl%2FBHgH2845arp%2FqQ%3D%3ASYmrx4zgi013elD4Kur7rNtPA95vsHDLSiR%2FpOODttw%3D
[DEBUG] 2019-02-18T17:23:05.904Z [storage-webdav] Load error http://cloud.test.com/remote.php/webdav/Keepass/Newdatabase.kdbx?requesttoken=BMGA%2F%2Fqh4RogORmcTsGo3J0Garcl%2FBHgH2845arp%2FqQ%3D%3ASYmrx4zgi013elD4Kur7rNtPA95vsHDLSiR%2FpOODttw%3D 0ms
[INFO ] 2019-02-18T17:23:05.904Z [open:/Keepass/Newdatabase.kdbx on cloud.test.com] Storage load error network error
[ERROR] 2019-02-18T17:23:05.904Z [open-view] Error opening file network error

**Comment by e-fik123** [comment]
My cloud is behind proxy.
Fixed by adding to config.php
'overwriteprotocol' => 'https',

**Comment by nicoroud** [comment]
Thank you so much !
I searched for a solution for a long time without finding anything and this work like a charm.
Many many thanks !

**Comment by JMPJNS** [comment]
i added 'overwriteprotocol' => 'https' to my config.php but i still get the network error, any other things i need to add? (using the nextcloud docker image)

**Comment by jonaseberle** [comment]
Firefox reported a Content-Security-policy problem before (connect-src 'self'...) but the underlying problem was as indicated here: The nextcloud generated a http:// link. The work-around fixes that for me.

**Comment by CptDayDreamer** [comment]
@JMPJNS did you fix it? I still can't use WebDAV out of the cloud. I've also added the overwriteprotocol...
I try to access like this: https://$serverip.de/remote.php/webdav/Passwords.kdbx

**Comment by JMPJNS** [comment]
i switched from nginx proxy to caddy, that fixed it for me

**Comment by CptDayDreamer** [comment]
@JMPJNS Okay that seems to be problematic because I'm using the docker image of NextCloudPi and can't change these things...

**Comment by kleingeschrieben** [comment]
I had the same issue today...
For me it fixed the problem by adding:
```
  'overwrite.cli.url' => 'https://sub.domain.de',
  'overwriteprotocol' => 'https',
```
to the nextcloud /config/config.php file.
overwritepotocol alone wasn't enough.
At all i added now these components to the config.php:
```
  "overwritehost"     => "sub.domain.de",
  'overwrite.cli.url' => 'https://sub.domain.de',
  'overwriteprotocol' => 'https',
  "overwritewebroot"  => "/nextcloud",
```

**Comment by GitterDoneScott** [comment]
For reference, I'm using jwilder nginx-proxy and the Nextcloud 17 container and the only line I had to add to my config.php was:
'overwriteprotocol' => 'https',

**Comment by lordvalium** [comment]
i have the same problem, added all the lines, abut does not work to open a local file per webdav
