### ISSUE TITLE
Problem association kdbx after save

### ISSUE THREAD

**Issue by Momosquiton** [jhass/nextcloud-keeweb#98]
I run nextcloud ver. 15
After the nextcloud upgrade and Keeweb app upgrade after that i save the file, the file .kdbx is not associate on app and i can perform "maintenance:mimetype:update-db --repair-filecache" 
I have the file /config/mimetypemapping.json correct
I run the files:scan --all command

the problem persist

**Comment by jhass** [comment]
Do you use some kind of external/cloud storage? IME it can be necessary to reupload the file in that case :(

**Comment by Momosquiton** [comment]
no i not use... the db is store on nextcloud machine's disk..
I try to reupload the file

**Comment by aproposnix** [comment]
I'm having the same issue. I cannot get the file association to work. I've followed the instructions on github (adding the mimetype to the config + occ filescane). 

Other apps (like diocom and mindmap) are also registered in the mimetypes (they registered themselves btw) and they work. 

My server admittedly is older (stock Ubuntu 16.04) so my first thought is whether it's an issue with PHP 7.0 (vs. the new 7.1+).

I'm using no external storage. If you need some outputs, let me know please.

**Comment by jhass** [comment]
Looks like Dicomviewer uses a install/repair step: https://github.com/ayselafsar/dicomviewer/blob/master/lib/Migration/RegisterMimeType.php (https://github.com/ayselafsar/dicomviewer/blob/master/appinfo/info.xml#L29) Certainly something we could try, would be nice to know exactly when this is called and also if there's a way to cleanup after ourselves on uninstall.

"Mind map" (I guess you mean that one, couldn't find anything in "Mindmaps") uses the dynamically on every request approach I tried previously (https://github.com/ACTom/files_mindmap/blob/e8620e6e14e0bfd063252328541af3bb78a2e76a/lib/AppInfo/Application.php#L23). That slows down nextcloud a lot on big installs.

**Comment by motey** [comment]
Same problem here:
after modifying a keepass file within nextcloud-keeweb, association for this file is lost and i have to re-run `sudo -u www-data php occ files:scan --all`
@  NC 16.1 with nextcloud-keeweb  0.5.1.
My instance runs only the fileapp and nextcloud-keeweb app. available for testing

**Comment by Alexr03** [comment]
Same here.
Anyone figured it out?

**Comment by ho16** [comment]
Same problem here:
NC 16.0.1

**Comment by tikoflano** [comment]
I faced this issue when syncing the file from my Windows Keepass 2.x app

**Comment by All0ne** [comment]
had the same problem and after an hour I found a solution.

first check /config/mimetypemapping.json again, should look like this

{
    "km": ["application/km"],
    "kdbx": ["application/x-kdbx"]
}
(the km application is for mindmap)

then i also edit the /config/mimetypealiases.json
{
    "application/km": "mindmap",
    "application/x-kdbx": "keeweb"
}


now run
`occ maintenance:mimetype:update-js` 
server answer "mimetypelist.js is updated"
(found at [https://docs.nextcloud.com/server/16/admin_manual/configuration_mimetypes/index.html](url))

finally update database by
`occ files:scan --all`


I didn't check if all the steps were necessary. It works for me. I can manually upload and save changes via keeweb and ist associate kdbx on app.


ps.: do not use firefox in privacy mode, atm its not possbile to save changes.

**Comment by motey** [comment]
> had the same problem and after an hour I found a solution.

Can confirm @All0ne  solution. Worked for me.
Tested with nextcloud-keeweb app in browser and remote editing with Desktop app
Thanks a lot

**Comment by scroom** [comment]
We've been experiencing the bug as well but @All0ne workaround solved the problem for the moment. Thanks for your hints!

**Comment by afarrapeira** [comment]
I've had the same problem with Nextcloud 17.0.1, and @All0ne 's solution worked!

**Comment by SimJoSt** [comment]
@Momosquiton does the problem persist with the newest, just released version? https://github.com/jhass/nextcloud-keeweb/releases  
It changes and automates the way the file extension is registered.

**Comment by maurerle** [comment]
This issue can be closed, as it is fixed with the newer version and is stale.
